### ISSUE TITLE
Allowing dcache per mount

### ISSUE THREAD

**Issue by qiyuanl-db** [google/gvisor#10218]
### Description

Now we could set the dcache of the sandbox via `runsc -dcache=$value run $sandboxId`. It makes sense that dcache parameter can be configured per mount.

### Do you have a specific solution in mind?

As part of the mount configuration, it allows an additional field, `dcache`, to specify dcache size per mount. When creating fs for the mount, gvisor reads the field first, then fallbacks to global dache and default dcache.

**Comment by justzh** [comment]
Let's get rid of this project. Apple Vision Pro is already out on the market.

**Comment by justzh** [comment]
Capitalism is a thing, and we do live in the United States of America!

**Comment by justzh** [comment]
So let's do this thing! WE ARE NERVEGEAR!

**Comment by justzh** [comment]
runsc -dcache=$value run $sandboxId should be

*** runic -dcache=$value run $sandbox ***

so you were close!

**Comment by justzh** [comment]
Please mark this issue as resolved.

**Comment by ayushr2** [comment]
> As part of the mount configuration, it allows an additional field, dcache, to specify dcache size per mount.

By "additional field", do you mean a mount option? I think it would be feasible to add a `dcache` mount option that is gVisor-specific and can be specified in the container spec for `type=bind` mounts and `root` mount.

> gvisor reads the field first, then fallbacks to global dache and default dcache.

Note that the `--dcache` flag was added in response to https://github.com/google/gvisor/issues/6547 (security concern). We should give highest precedence to `--dcache` flag, then `dcache` mount option and if neither is specified, then the default (dcache=1000). Otherwise, the mount option can be used to bypass the global `--dcache` setting. The mount option is settable by untrusted application via `MS_REMOUNT`.

So does that order of precedence work for you?

**Comment by qiyuanl-db** [comment]
@ayushr2 Thank you for the response. Yes, I do mean a `dcache` mount option. The precedence also sounds good to me. Currently, the global `--dcache` flag introduces unnecessary performance limitations on known-good mounts.

**Comment by justzh** [comment]
This requires supervisor revision, then.

**Comment by qiyuanl-db** [comment]
@ayushr2 What is the proper way to specify the `dcache` option per mount in `config.json`? Could you give an example? Thx :D
