### ISSUE TITLE
`ip route del default` fails with "RTNETLINK answers: Operation not supported" (gVisor release-20240610.0)

### ISSUE THREAD

**Issue by avizack18** [google/gvisor#10547]
### Description

I'm encountering an error when trying to delete the default route using `ip route del default` in gVisor version release-20240610.0. The command returns the following message:

```
RTNETLINK answers: Operation not supported
```

### Steps to reproduce

1. Install gVisor version release-20240610.0.
2. Attempt to delete or add the default route using:
   ```
   ip route del default
   ip route add default via 192.168.4.90
   ```
3. Observe the "RTNETLINK answers: Operation not supported" error message.

### runsc version

```shell
runsc version release-20240610.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
24.0.5
```

### uname

5.15.0-112

**Comment by milantracy** [comment]
thanks!

it has been the known issue, both netlink RTM_NEWROTE and RTM_DELROUTE are not supported.

I have been working on RTM_NEWROUTE, a PR could be found at https://github.com/google/gvisor/pull/10539

Please feel free to create a PR if you have anything on RTM_DELROUTE, otherwise, I will work on it after RTM_DELROUTE

**Comment by milantracy** [comment]
RTM_DELROUTE should be working with the netstack now w/ the commit https://github.com/google/gvisor/commit/f681bcc095fb168ae26f9af44004e4e67993a393
