### ISSUE TITLE
runsc-sandbox runs as root by default, as 'nobody' with --directfs false

### ISSUE THREAD

**Issue by chetan-reddy** [google/gvisor#10839]
### Description

With directfs enabled (now the default), runsc-sandbox keeps running as root and does not drop to user 'nobody'. I couldn't find much documentation about this except for a sentence on [this blog entry](https://opensource.googleblog.com/2023/06/optimizing-gvisor-filesystems-with-directfs.html)

> We also had to give the sandbox the same privileges as the gofer (for example CAP_DAC_OVERRIDE and CAP_DAC_READ_SEARCH), so it can perform the same filesystem operations.

Could you please explain the implications of a compromised sandbox running as 'root' vs 'nobody'? Are they similarly limited in their capabilities because of all the other defenses, or will a compromised 'root' Sentry be significantly more capable than a compromised 'nobody' Sentry?
I read the [security page](https://gvisor.dev/docs/architecture_guide/security/) but didn't find any info about this. Is it explained elsewhere?

**Comment by ayushr2** [comment]
Directfs is a feature which makes the sandbox process perform all the filesystem operations, instead of using the gofer to do so. It entails that the sandbox process is run in a way that it can access the container filesystem and perform operations on behalf of the application with arbitrary UID/GIDs.

For the sake of not overloading the term "root", I am going to call the root user namespace as "initial user namespace", which is the first user namespace created when the system boots up.

The sandbox process (named `runsc-sandbox`) almost always runs **in a new userns** (not initial userns). Some exceptions are when `--network=host` is being used. I am going to assume you are **not** using `--network=host` (which is not the default). User namespaces are used to isolate capabilities. So the sandbox process does not have capabilities in the initial userns (on the host).

With directfs too, the sandbox process runs in a new userns. See https://github.com/google/gvisor/blob/2511e2e937ec956f836909c33e1ff2ba74fd3fdc/runsc/container/container.go#L1779-L1815

There are 2 differences between directfs on/off:
1. With directfs, the sandbox's userns is created with identity mappings (see `getIdentityMapping()`). This is to ensure that all the UIDs used by the application are mapped in the sandbox's userns so that when it performs operations with those UIDs, they are translated correctly in the host kernel.
2. With directfs, the sandbox process runs as UID=0 in the new userns. This is to ensure that the sandbox has the permissions to modify the container filesystem on behalf of the application. This UID=0 in sandbox userns is mapped to UID=0 in the initial userns (because identity mappings), which is why you observe it as root on the host. However, the sandbox process's capabilities are still isolated by its user namespace. So the sandbox should not have any capabilities on the host.

It is also important to note that, with directfs=true, the sandbox is still running in a new mount namespace which is completely empty. The sandbox's mount namespace [doesn't even have /proc filesystem](https://github.com/google/gvisor/blob/2511e2e937ec956f836909c33e1ff2ba74fd3fdc/runsc/cmd/boot.go#L486-L487). At sandbox start, we ensure it doesn't have any open file descriptors to directories: https://github.com/google/gvisor/blob/2511e2e937ec956f836909c33e1ff2ba74fd3fdc/runsc/cmd/boot.go#L615-L660

The container filesystem is owned and mounted by the gofer process in the gofer's mount namespace. Upon container start, the gofer then selectively donates certain file descriptors to the sandbox for it to use and conduct its business.

**Comment by chetan-reddy** [comment]
Thanks for the detailed response. Are there really no security advantages to dropping to `nobody`? If so, why even bother to drop to `nobody` when run with `--directfs false`

On a related note, if by default runsc-sandbox doesn't run as `nobody` anymore, please consider updating this blurb on the [install page](https://gvisor.dev/docs/user_guide/install/) 

> Note: It is important to copy runsc to a location that is readable and executable to all users, since **runsc executes itself as user nobody** to avoid unnecessary privileges. The /usr/local/bin directory is a good place to put the runsc binary.

Lastly, if in the future runsc chooses to enable by default a feature that compromises security for speed, I hope the flags to run it in the most secure mode are presented on the install page.

**Comment by ayushr2** [comment]
I think there are security advantages of dropping to `nobody` (or rather, running the sandbox without any capabilities). Note that the UID is just an implementation detail; the difference is that with directfs the sandbox process is running with more capabilities (necessary to access the filesystem). So yes, directfs does relax the security model in that way. But the sandbox's capabilities should be contained by its user namespace.

I will update the website.
