### ISSUE TITLE
'ip route get' on debian/ubuntu: "RTNETLINK answers: Operation not supported"

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#1099]
After @ianlewis fixed  #507 and #769, we still see below command failed:

$ ip route get 1.1.1.1

It seems that route filtering is not supported.

**Comment by ianlewis** [comment]
Is it just the 'ip route get ADDRESS' command that you need? Do you need any of the other commands or filtering options?

**Comment by ianlewis** [comment]
There may end up being multiple issues because I don't think our netlink support is robust enough to support the 'ip route get' command. Before we even get there, the first issue seems to be an unsupported socket option

The call below is something like:
setsockopt(sock, SOL_NETLINK, NETLINK_EXT_ACK, ...)

```
I1030 01:05:12.513587    5036 x:0] [   1] ip E setsockopt(0x3 socket:[1], 0x10e, 0xb, 0x7f43594d6c94, 0x4)
I1030 01:05:12.513605    5036 x:0] Unsupported syscall: setsockopt, regs: rax:18446744073709551578  rbx:94261284848992  rcx:140140161993322  rdx:11  rsi:270  rdi:3  rsp:139927237782648  rbp:94261284848996  r8:4  r9:140140162788736  r10:139927237782676  r11:582  r13:94261284709596  r14:139927237783392  r15:139927237783048  rip:140140161993322  rflags:582  orig_rax:54  cs:51  ss:43  fs_base:140140160953920
I1030 01:05:12.513890    5036 x:0] [   1] ip X setsockopt(0x3 socket:[1], 0x10e, 0xb, 0x7f43594d6c94, 0x4) = 0x0 errno=92 (protocol not available) (292.75µs)
```

I think the call is here:
https://github.com/shemminger/iproute2/blob/6754e1d9783458550dce8d309efb4091ec8089a5/lib/libnetlink.c#L213

**Comment by tanjianfeng** [comment]
> Is it just the 'ip route get ADDRESS' command that you need? Do you need any of the other commands or filtering options?

We only need this specific command now. Not sure if anybody else has different requirements.

**Comment by ianlewis** [comment]
It looks like I'm going to need to focus on other work for a while. I'd be happy to review a PR if you could provide a fix.
