### ISSUE TITLE
Let user-network stack support CRI-Pod

### ISSUE THREAD

**Issue by ThunderYe** [google/gvisor#123]
Hi all,
      I am working on gVisor supporting CRI-Pod mode, there is a problem, concern go-stack(epsocket),it will collect network interface within Sandbox-root container stage ,but in that time ,there are no any useful NIC or IP/Route info in that netns ,for CNI has not be called yet! 

You see ,till now only the Host-int mode can work ,for it  just use Host-net-stack ,there are nothing to do!

   I have a method ,delay the stack-setup timing ,when the APP-container is running . 

I select a  time slice ,just when a APP call a "Socket" inet-syscall , for Sandbox use Pasue Image it must not call Socket syscall, Only the APP will call this syscall and "Socket"must be the first called syscall for all TCP/IP APP. 

How do you think about this idea?

**Comment by fvoznika** [comment]
The network needs to be setup before the root container starts. The network can be configured in two ways:
1. **Before ```create``` is called:** create netns, configure it and send it in the [OCI spec](https://github.com/opencontainers/runtime-spec/blob/1722abf79c2f8f2675f47367f827c6491472cf27/specs-go/config.go#L184). Then the runtime will create the sandbox inside this namespace and read the configuration from there.
1. **Let the runtime create netns**: an empty network namespace is created by the runtime and it's configured when the [prestart hook](https://github.com/google/gvisor/blob/f6274804e14ece853c952cb71fde73dfb06b733a/runsc/container/container.go#L362) is called. This is how docker does it by default.

If you note, network configuration is already delayed until after the prestart hook special to support the case above. I'd recommend using one of the options above with CNI otherwise it's hard to know when the network is ready to be used and when the container can start. Please let me know if this works for you.

**Comment by ThunderYe** [comment]
Thanks a lot  fvoznika for the quick feedback!

I think there are difference between docker-network and CRI-OCI-CNI mechanism, there  are 3 stage:  
1) Create a runsc instance with Pause Image as Pod-sandbox; 
2) CNI is called for the Pod-sandbox-netns; 
3) Create  the APP-container in the Pod-Sandbox.
 CNI will work just between CRI-PosSandbox and APP-Container, there are no hook plugin point!

So concern the CRI(kubelet or crictl) build a Pod, it will call runsc twice, first(runsc run) build a runsc instance(our own sandbox + root-container+pause-container),second (runsc run)build the app-container inside previous runsc-sandbox by setting the sandboxID in the second's OCI json configuration  .

You see ,we can setup the network stack before the root container starts,but at that time CNI has not worked, we has no NIC and IP/Route info, only after CNI is called , then (runsc  run) is called the second time for APP-container ,we can see the CNI's result（NIC,IP route...).

I suggest append a netns info collecting in APP-container(sencond runsc running),just neighbor the "ShouldCreateSandbox" code ,when runsc found it need not setup its own sandbox ,then this time it is called for a APP-container.

**Comment by fvoznika** [comment]
It's possible to create and configure the netns before the pause container is executed. This is how CRI-containerd works. You can check [gvisor-containerd-shim](https://github.com/google/gvisor-containerd-shim) and [containerd](https://github.com/containerd/cri) to see how it's done. Depending on what you're trying to achieve, you might be able to use gvisor-containerd-shim straight out of the box.

**Comment by Random-Liu** [comment]
@ThunderYe We configure CNI before creating root container in containerd. https://github.com/containerd/cri/blob/master/pkg/server/sandbox_run.go#L129

If you are using containerd, you shouldn't have problem with this.

**Comment by ThunderYe** [comment]
Thanks a  lot ,@Lantao Liu @fvoznika 
In fact ,I am working on Pouch Project, unfortunately  it will start Pod-sandbox before setup Pod network.Then I have to persuade  them to follow containerd' method OR delay the network init as I described previously.

Pouch's code is here:
https://github.com/alibaba/pouch/blob/d09f9f75414ee4449ad743a3a8242d6485a80cfc/cri/v1alpha2/cri.go#L343

**Comment by ThunderYe** [comment]
Seems gVisor need not change the Net stack configuration procedure ,for containerd and cri-o both setup the pod-network between Pod-sadbox started .
Let me close the issue, try to persuade the Pouch's guys .
Close the Issue!
