### ISSUE TITLE
sentry io performance

### ISSUE THREAD

**Issue by GuhuangLS** [google/gvisor#142]
Hi 
    I 'm  GuhuangLS  from ant finance；  I  found  some issues:io perfomance is poor;
    one read takes 113784 cycles;  2nd read takes 29976 cycle too;
    If mmap one file and memset ,  then   read  it,   the read takes 10000cycle;
    and only mmap  method  supports  pagecache;   
    Normal  file operations(read/write) can't create pagecache;
    Will sentry  to be  improved  about   these?
     Thanks;

**Comment by ianlewis** [comment]
Hi @GuhuangLS! Thanks for creating the issue.

Do you have more details about how you are performing your test? Maybe a [gist](http://gist.github.com) or something like that?

**Comment by amscanne** [comment]
Hi Guhuang,

Yes -- there are page cache related changes in flight right now (e.g. [1]). I'm not sure they will be initially connected to standard reads and writes, but it lays the groundwork to do so.

@nixprime can share more details.

[1] https://gvisor-review.googlesource.com/c/gvisor/+/15406

**Comment by GuhuangLS** [comment]
> Hi @GuhuangLS! Thanks for creating the issue.
> 
> Do you have more details about how you are performing your test? Maybe a [gist](http://gist.github.com) or something like that?

Hi   Ianlewis
    1.   This is testcase : 
`
#define RW_SIZE 4096
#define MMAP_SIZE 200 * 1024 * 1024
#define MALLOC_SIZE 4096  + 1024
#define READ_TIME  8
#define ENABLE_CACHE
char buf[8192];
int main(int argc, char *argv[])
{
	int fd = -1, i, j;
	int ret;
	void *addr;

	fd = open("/home/test.file", O_RDWR | O_CREAT, 0777);
	if (fd < 0) {
		printf("open file error:%d\n", fd);
		return -1;
	}
#ifdef ENABLE_CACHE
	addr = mmap(NULL, MMAP_SIZE , PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
	if (addr < 0) {
		printf("mmap file error:%d\n", addr);
		return -1;
	}

	memset(addr, 'A', MMAP_SIZE);
#endif
	for (i = 0; i < READ_TIME; i++) {
		ret = read(fd, buf, RW_SIZE);
		if (ret <=0 )
			printf("write count error:%d\n", ret);
	}

	close(fd);
	return 1;
}
`
     2. I add rdtsc()  to get cpu cycle  in pkg(not sentry)  io  path,  or sentry path uses gvisor.googlesource.com/gvisor/pkg/sentry/time

`
#include "textflag.h"
TEXT ·Rdtsc(SB),NOSPLIT,$0-8
	// N.B. We need LFENCE on Intel, AMD is more complicated.
	// Modern AMD CPUs with modern kernels make LFENCE behave like it does
	// on Intel with MSR_F10H_DECFG_LFENCE_SERIALIZE_BIT. MFENCE is
	// otherwise needed on AMD.
	LFENCE
	RDTSC
	SHLQ	$32, DX
	ADDQ	DX, AX
	MOVQ	AX, ret+0(FP)
	RET
`

   3.   I  found  interface takes too time at firt syscall invoke when containers run :  one 
            interface > 10000cycle;  
         When i run testcace 2nd time at the same givsor container,   1st read , interface 
            cycle is 5000cycle  ; 2nd read  interface cycle is 300~800cycle;

**Comment by GuhuangLS** [comment]
Hi amscanne   
    Thanks;   mem  reclaim offered by nixprime  at the patch;

     Will hot/cold page manangement  to be added to reclaim module;?

     I see writeback contained in reclaim module;  
     Will  independent writeback mechanism be devloped?

     According to test result,  cache is useful  to  standard reads and writes;

**Comment by chenggangqcg** [comment]
Could we use the current cache policy to support read() operation for the readonly files?
In current version, the "page cache" is only effective for mmap() operation.

**Comment by amscanne** [comment]
Read-ahead style page cache is complicated because of the reclaim implications. And if we don't reclaim, then memory usage can grow in an unbounded way, and we also lose the many process-like properties of the sandbox.

The current patch queue adds support for "memory pressure" and basic reclaim/eviction. I believe that is minor follow-on work to enable it for a read-ahead page cache. (Ideally a pretty simple function call to asynchronously start loading the page cache ahead of an uncached read.)

Re: hot/cold page management, no, I don't think so. I believe that any mapped regions with reference counts > 0 will be retained. For the read path (e.g. refs = 0), I don't know exactly what the plan is, but it seems like the obvious solution would be structure as an LRU, since we are in the access path.

Re: writeback, yes, I believe that you would need to writeback on eviction. I'm not sure about an independent (outside of reclaim) writeback mechanism.

If there's interest to help drive these or provide feedback, it would be great to discuss with @nixprime.

**Comment by GuhuangLS** [comment]
Thanks    Amscanne     
     Now  I  understood more about io ；

     Hi   nixprime   @nixprime  
     Ask for advice;
     Are  the  writeback and read/write cache  in the plan ?
     Thanks;

**Comment by nixprime** [comment]
To clarify the behavior of the page cache:

1. (All of the following only applies to gofer-backed files for which host file descriptors are not avaliable.)

2. When a file is mmapped and the resulting mapping is touched, the sentry caches the touched pages (and possibly some following pages, as a readahead mechanism) into the sentry page cache. This is required to implement mmap.

3. When a file is read from or written to with an I/O syscall such as read() or write(), pages that are present in the page cache as a result of (2); I/O will only go directly to the backing file if cached pages are not available.

4. When all mappings of a file page are munmapped, cached pages are written back and evicted immediately.

The upcoming patch series noted by @amscanne changes (4) so that, when memory pressure information is available from the host Linux kernel, cached pages are written back and evicted only when memory pressure is present. This host kernel signal is binary and edge-triggered; in other words, it's a signal that "memory pressure exists right now" (more precisely, "the host kernel is performing memory reclaim"). Because of the low information content of this signal, we respond to this signal by evicting *all* cached pages that would be have evicted by the previous version of (4). This is why the patch series doesn't attempt to prioritize which pages should be evicted. Caching pages on read() wouldn't change this.

There is an in-progress patch that follows the above series that causes read() (and related syscalls such as pread(), readv(), etc.) to cache pages when memory pressure information is available. It does not change write(). This is because caching on read() changes the behavior of a small read from "a small read from the backing file to application memory" to "a moderately-sized read from the backing file to the page cache", and the cost of this backing file read is expected to be dominated by the overhead of the RPC (that is, the marginal cost of the larger read is small). However, caching on write() changes the behavior of a small write from "a small write from application memory to the backing file" to "a moderately-sized read from the backing file to the page cache, plus a moderately-sized write to the backing file from the page cache at some point in the future", and this is potentially very expensive.

**Comment by nixprime** [comment]
@GuhuangLS, can you clarify a few more points about your experimental configuration:

- What platform are you using? Ptrace, KVM, or something else?

- What is the filesystem being accessed, and how are you accessing it? Is it the local host filesystem, through runsc/fsgofer, or something else?

- Where are you adding calls to RDTSC

**Comment by GuhuangLS** [comment]
Hi  nixprime  @nixprime 

> * What platform are you using? Ptrace, KVM, or something else?
    platform independent
> * What is the filesystem being accessed, and how are you accessing it? Is it the local host filesystem, through runsc/fsgofer, or something else?
1.File : /home/test.file   
2.fs: rootfs
3.read path: gr3 userspace:read() -> 
                  gr0: fs/file.go -> file_overlay.go -> gofer/file.go->inode_cached.go->usermem->safemem->secio->fd->syscall->
                  hr0:host;
> * Where are you adding calls to RDTSC

I add rdtsc at read path  which uses interface:
1st read test: add here
`
	Time2 := time.Rdtsc()
		n, err :=  f.inodeOperations.cachingInodeOps.Read(ctx, file, dst, offset)
		Time3 := time.Rdtsc()
		log.Debugf("-----------: file gofer : time: readv:%v %v---------", Time2 - Time1, Time3 - Time2)
`
2nd read test : close last log.Debugf at 1 point;  add rdtsc at CachingInodeOperations Read()
`
func (c *CachingInodeOperations) Read(ctx context.Context, file *fs.File, dst usermem.IOSequence, offset int64) (int64, error) {
	Time1 := time.Rdtsc()
        .........
	n, err := dst.CopyOutFrom(ctx, &inodeReadWriter{ctx, c, offset})
	Time3 := time.Rdtsc()
	// Compare Linux's mm/filemap.c:do_generic_file_read() => file_accessed().
	c.TouchAccessTime(ctx, file.Dirent.Inode)
	log.Debugf("-----------: file inode cache: time: readv:%v %v %v---------", Time2 - Time1, Time3 - Time2, Time3 - Time1)
`
Other test case:   Copy  takes 20000cycle at 1st invoke
`
func CopySeq(dsts, srcs BlockSeq) (uint64, error) {
	var done uint64
	for !dsts.IsEmpty() && !srcs.IsEmpty() {
		Time1 := time.Rdtsc()
		dst := dsts.Head()
		src := srcs.Head()
		Time2 := time.Rdtsc()
		n, err := Copy(dst, src)
		done += uint64(n)
		if err != nil {
			return done, err
		}
		Time3 := time.Rdtsc()
		dsts = dsts.DropFirst(n)
		srcs = srcs.DropFirst(n)
		Time4 := time.Rdtsc()
		log.Debugf("----------- CopySeq: time:%v %v %v %v---------", Time2 - Time1, Time3 - Time2, Time4 - Time3)
`

**Comment by GuhuangLS** [comment]
nixprime @nixprime
  ”There is an in-progress patch that follows the above series that causes read() (and related syscalls such as pread(), readv(), etc.) to cache pages when memory pressure information is available. It does not change write(). “
        
       The patch adds  cache only for standard read syscall  which  can create pagecache without mmap?
       Thanks

**Comment by nixprime** [comment]
> The patch adds  cache only for standard read syscall  which  can create pagecache without mmap?

The patch in question affects all syscall-driven reads: read(), pread(), readv(), preadv(), etc. Yes, it allows the sentry to read pages into the sentry page cache whether or not those pages are mmapped. However:

> read path: gr3 userspace:read() ->
gr0: fs/file.go -> file_overlay.go -> gofer/file.go->inode_cached.go->usermem->safemem->secio->fd->syscall->
hr0:host;

None of the patches involved affect this path. As previously mentioned:

> 1. (All of the following only applies to gofer-backed files for which host file descriptors are not avaliable.)

When host file descriptors *are* available, as in this case, the sentry page cache is *never* used. Instead, mmap(), read(), write(), etc. use the host file descriptor. This ensures that the file's contents as seen from inside the sandbox remain consistent in the presence of file access and mutation from parties outside the sandbox, via the host kernel's page cache. It also allows the host page cache to manage caching, and avoids the memory overhead of caching file pages twice (in both the host and sentry page caches). There are still things we can do to make this path faster, but the behavior of page caching in this case is unlikely to change.

> - What platform are you using? Ptrace, KVM, or something else?
> platform independent

Are you sure? This path means that every read() results in a host system call, for which the ptrace and KVM platforms have fairly different performance characteristics.

**Comment by GuhuangLS** [comment]
Hi    nixprime  
`
The patch in question affects all syscall-driven reads
`
Can Data be consistent between read and write？
`
avoids the memory overhead of caching file pages twice (in both the host and sentry page caches)
`
host syscall  uses direct io, only  sentry keep cache?

`
This ensures that the file's contents as seen from inside the sandbox remain consistent in the presence of file access and mutation from parties outside the sandbox,
`
Can you  show  the detail more?  which scene need to be accessed from outside and inside sandbox ?

Thanks;

**Comment by chenggangqcg** [comment]
“avoids the memory overhead of caching file pages”
===========
We might use DAX to avoid host's pagecache.

**Comment by GuhuangLS** [comment]
Hi nixprime
”This ensures that the file's contents as seen from inside the sandbox remain consistent in the presence of file access and mutation from parties outside the sandbox,”
I have a doubt：
“2 givsor container A and B ;
A has rw permission about file  x access;
B has r permission about file  x access;
B reads data to its buf from file x; A writes  new data to the file x; B keeps old data at user buffer;
How can we to keep data consistent? ”

**Comment by GuhuangLS** [comment]
Hi nixprime . @nixprime
Direct io doesn't work now?  
I see  only cachePolicy.usePageCache() to determine wether to use inode cached layer, is that ?

**Comment by nixprime** [comment]
> Can Data be consistent between read and write？

Reads and writes are always consistent *within* the sandbox. The policies in question only affect when pages become cached; if a page is cached, it will be used for both reads and writes.

> host syscall uses direct io, only sentry keep cache?

This wouldn't address any of the other reasons to favor the host page cache over the sentry page cache. There are other reasons as well; for example, even if we had more precise signals on when and how much to evict, we'd have difficulty prioritizing pages for eviction because we don't have access to page table accessed bits.

> B reads data to its buf from file x; A writes new data to the file x; B keeps old data at user buffer;

Consistency with parties outside the sandbox requires host file descriptors, such that the sentry page cache is not used. (The host page cache is shared by both sandboxes, so it can and does ensure consistency.) If two sandboxes are sharing a mutable filesystem, both must be aware that they're sharing it mutably (for the root mount, this requires `runsc --file-access=shared`); this causes the `cache=remote_revalidating` mount option to be used for gofer mounts, which requires the gofer to supply host file descriptors (see gofer.NewFile in //pkg/sentry/fs/gofer/file.go).

> How can we to keep data consistent? ”
> （1）inotify? Inotify mechinism could keep data consistent with different containers；

inotify requires host file descriptors too.

> （2）buffer io and direct io both supported:
> file shared to be accessed by dio, file private by bio?
> Or let users decide which one to use?
> （3）Are the files shared and private at the same dir ?

I'm not sure what you mean.

> Direct io doesn't work now?
> I see only cachePolicy.usePageCache() to determine wether to use inode cached layer, is that ?

Do you mean using `O_DIRECT` *within* gVisor? I don't think it's implemented.

**Comment by GuhuangLS** [comment]
Hi nixprime . @nixprime
"we'd have difficulty prioritizing pages for eviction because we don't have access to page table accessed bits."
At sentry/platform/ring0/pagetables/pagetables_x86.go: Set () ： 
access bit is set at pte;   
Can we use this information?

**Comment by GuhuangLS** [comment]
issue is  ok
