### ISSUE TITLE
userns-remap default is unsupported

### ISSUE THREAD

**Issue by D-Nice** [google/gvisor#145]
What I would consider an important security setting, appears unsupported by runsc. When I set `"userns-remap": "default"` in the daemon conf file, trying to run any container with runsc as the runtime causes it to fail (default runtime works fine). 

Commands attempted:
```
$ docker run --runtime=runsc --rm -v /root/:/tmp/root -u root -it ubuntu bash
docker: Error response from daemon: OCI runtime create failed: /var/lib/docker/100000.100000/runtimes/runsc did not terminate sucessfully: reading spec: mount option "noexec" is not supported: &{/dev/shm bind /var/lib/docker/100000.100000/containers/5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a/mounts/shm [rbind rprivate noexec nosuid nodev]}
```

```
$ docker run --runtime=runsc hello-world
docker: Error response from daemon: OCI runtime create failed: /var/lib/docker/100000.100000/runtimes/runsc did not terminate sucessfully: unknown.
ERRO[0000] error waiting for container: context canceled 
```

Docker version:
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.12
 Git commit:        
 Built:             Sun Mar 10 23:16:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12
  Git commit:       v18.09.3
  Built:            Sun Mar 10 23:16:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

uname (void linux)
`
Linux void-nvme2 4.20.16_1 #1 SMP PREEMPT Thu Mar 14 20:39:59 UTC 2019 x86_64 GNU/Linux
`

Debug Log for ubuntu container:

```
I0320 18:50:48.840255    8593 x:0] ***************************
I0320 18:50:48.840315    8593 x:0] Args: [/usr/local/bin/runsc --debug-log=/tmp/runsc/ --debug --strace --root /var/run/docker/runtime-runsc/moby --log /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a/log.json --log-format json create --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a --pid-file /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a/init.pid --console-socket /tmp/pty571071343/pty.sock 5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a]
I0320 18:50:48.840337    8593 x:0] Git Revision: 87cce0ec08b9d629a5e3a88be411b1721d767301
I0320 18:50:48.840346    8593 x:0] PID: 8593
I0320 18:50:48.840355    8593 x:0] UID: 0, GID: 0
I0320 18:50:48.840362    8593 x:0] Configuration:
I0320 18:50:48.840369    8593 x:0] 		RootDir: /var/run/docker/runtime-runsc/moby
I0320 18:50:48.840376    8593 x:0] 		Platform: ptrace
I0320 18:50:48.840386    8593 x:0] 		FileAccess: exclusive, overlay: false
I0320 18:50:48.840395    8593 x:0] 		Network: sandbox, logging: false
I0320 18:50:48.840403    8593 x:0] 		Strace: true, max size: 1024, syscalls: []
I0320 18:50:48.840411    8593 x:0] ***************************
W0320 18:50:48.841643    8593 x:0] AppArmor profile "docker-default" is being ignored
W0320 18:50:48.841659    8593 x:0] Seccomp spec is being ignored
W0320 18:50:48.841683    8593 x:0] FATAL ERROR: reading spec: mount option "noexec" is not supported: &{/dev/shm bind /var/lib/docker/100000.100000/containers/5d4b42d548e56a6057c078c0605b1127ec6d0a70e92355a5f06877ef6abacc1a/mounts/shm [rbind rprivate noexec nosuid nodev]}
```

**Comment by fvoznika** [comment]
runsc always runs the container inside a user namespace that is isolated from the host. The user namespace exists only inside the sandbox and has no connection to the host. Therefore, there is no need to use `userns-remap` to isolate containers from the host. There is only one case where gVisor uses the host's user namespace that I explain below.

The gVisor kernel appears just like a regular process to the host kernel, I'll call it sandbox process from now on. Containers runs inside this process in their own world that is isolated from the host. To further protect it, the sandbox process is put inside a terminal chroot, on a new user namespace which maps the sandbox to the user `nobody` in the host, and wraps the process with seccomp filters. This is to protect against malicious code that may have compromised gVisor. A compromised gVisor runs in a more restricted environment that most containers do.

When `--network=host` is used though, the sandbox process must run in the user namespace specified by docker because it needs to access host's network stack. The user namespace inside the sandbox continues to be isolated from the host, but a compromised gVisor will be running in the docker's supplied user namespace. On the other hand, `--network=host` is already less safe than the default `--network=sandbox` by giving containers access to the host's network stack, so I'm not sure `userns-remap` would be much of use in this case.

**Comment by D-Nice** [comment]
I would hope that is the case, but that has not been my experience thus far.

Running

`docker run --runtime=runsc --rm -v /root/:/tmp/root -u root ubuntu /bin/touch "/tmp/root/rootfile"`

Yields the creation of the rootfile under my hosts `/root` path. I think we understand what other chaos this can cause and it effectively yields any user capable of running docker, root. If the aforementioned isolation held, I would expect the above to not be possible.

For example, under the default runc runtime, enabling `userns-remap` results in a permissioin denial.

**Comment by amscanne** [comment]
Can't a user just do: "docker run --userns=host --privileged" for root access anyways? I like the idea of supporting the userns here (so that the gofer is at least in the provided userns, and the noted touch don't work) but you should probably assume that any user capable of talking to the Docker daemon has effective root access. The configuration file setting is providing only a default IIUC.

**Comment by D-Nice** [comment]
Yes, you're correct, but the remap at least provides mitigatation against some malicious containers, which can have that volume and user setup from a Dockerfile etc... whilst running the container privileged cannot be done from the container or Docker file itself (if I'm not mistaken).

**Comment by amscanne** [comment]
Can the container metadata actually specify this kind of mount? The docker documentation seems to suggest that it cannot re: the VOLUME keyword in Dockerfiles:

"The host directory is declared at container run-time: The host directory (the mountpoint) is, by its nature, host-dependent. This is to preserve image portability, since a given host directory can’t be guaranteed to be available on all hosts. For this reason, you can’t mount a host directory from within the Dockerfile. The VOLUME instruction does not support specifying a host-dir parameter. You must specify the mountpoint when you create or run the container."

It seems like this is just declared some directory a VOLUME, which you still need to attach at create or run time.

(There are good suggestions and ideas in this thread, I just want to understand the exact exposure.)

**Comment by D-Nice** [comment]
Yes, I guess you are correct in this regard it would still fall down to a careless user (good point regarding unspecified host-dir). However, since runsc aims to be a sandbox/security oriented runtime, I would still expect at the very least matching security capabilities to runc, and believe `userns-remap` is one of the most basic expected.

Or if there is some other alternative way, where I can forbid any root capabilities/actions from occurring on the host when using runsc. The possiblity of any root side effect to me, is scary, hence why I'm looking into gVisor.

**Comment by amscanne** [comment]
Yes, I agree that this feature should apply to the gofer (which is doing the file access above). Currently, the sentry will drop permissions and execute as nobody which what I believe is failing. I think it just needs to check whether it is a user namespace already and not drop permissions. (But how do you know if the user namespace is sufficiently? Maybe you're in a nested privileged container. Ugh.)

**Comment by avagin** [comment]
@D-Nice could you try out this patch https://gvisor.googlesource.com/gvisor/+/e5c934fd76acb8c31041f473152a2b61287b09ad%5E%21/

**Comment by D-Nice** [comment]
@avagin I'll give it a go hopefully some time today and let you know

**Comment by D-Nice** [comment]
@avagin still not working for me

```
docker: Error response from daemon: OCI runtime create failed: /usr/local/bin/runsc did not terminate sucessfully: reading spec: mount option "noexec" is not supported: &{/dev/shm bind /var/lib/docker/1000.1000/containers/56754f9138a10856bacbdbb5ae4124fcb9ca51d9eb72fc100f3809c02ce63ab8/mounts/shm [rbind rprivate nodev noexec nosuid]}
: unknown.
```

built on commit 654e878abba174d8f7d588f38ecfd5a020bf581e and your patch applied. Current head failed to build for me at all so reverted to that commit.

**Comment by avagin** [comment]
@D-Nice Could you double check that you compile with my patch and place a new runsc  binary to the right place. This error should not be reported with my patch.

**Comment by D-Nice** [comment]
i will retry, I definitely built it with the patch, but I tried renaming the binary and re-pointing to the new binary in daemon.json instead of just replacing it.

**Comment by avagin** [comment]
Maybe you forgot to restart a docker daemon.

**Comment by D-Nice** [comment]
restarted it multiple times in fact, but i'll retry again without this naming complication.

**Comment by D-Nice** [comment]
Hmmm, seems the runtime would default to runsc, even if I changed path to runsc_ until I moved the original runsc binary out. The error at least differs now. It works fine as regular runsc when userns-remap is not enabled in the conf.

```
$ sudo docker run --runtime=runsc --rm -v /root/:/tmp/root -it ubuntu bash
docker: Error response from daemon: OCI runtime start failed: /usr/local/bin/runsc_ did not terminate sucessfully: starting container: starting root container: starting sandbox: mount submount "/tmp/root": creating mount with source "/root": input/output error
```

**Comment by avagin** [comment]
@D-Nice could you attach runsc logs?
https://github.com/google/gvisor#debugging

**Comment by D-Nice** [comment]
[runsc-debug.tar.gz](https://github.com/google/gvisor/files/3035781/runsc-debug.tar.gz)

uploaded as tar.gz

**Comment by avagin** [comment]
@D-Nice you try to bind-mount /root into a container, but the root user of this container doesn't have enough rights to access the host /root directory.

You can try to remove this bind-mount from options:
$ sudo docker run --runtime=runsc --rm  -it ubuntu bash

**Comment by D-Nice** [comment]
The above works, and mounting a path belonging to the user it's been remapped to works. So in that respect it now matches the runc behaviour, however, the mounting of the /root dir also works with runc but not runsc, but I guess that is safer (no access, rather than just no write) anyways, if the goal is not to match the regular runtime behaviour completely, and I personally probably wouldn't be doing that, but was using it as the test basis.

**Comment by D-Nice** [comment]
I presume this is now in the nightlies since the above linked commit? 

Thank you all for your time and effort, as far as I'm concerned I'm satisfied with this current remap support.

**Comment by avagin** [comment]
> I presume this is now in the nightlies since the above linked commit?

Here is one more patch on review. I think it will be merged today or tomorrow:
https://gvisor-review.git.corp.google.com/c/gvisor/+/15960

**Comment by avagin** [comment]
All changes have been pushed into the upstream repo.
