### ISSUE TITLE
When and how the gVisor container communicate with the Docker Commpoments?

### ISSUE THREAD

**Issue by younaman** [google/gvisor#1555]
Hello everyone!I am a green hand about gVisor,I have knew that in a normal container,some operations will trigger the container to communicate with the Docker compoments,but in the gVisor,I want to know when and how the gVisor container will communicate with the Docker Commpoments such as docker-proxy/containerd and so on?Can I find these communications in the gVisor debug information?I would be appreciate if you could give me some suggestions!Thanks a lot!

**Comment by kevinGC** [comment]
When using gVisor with Docker, containerd communicates with [gvisor-containerd-shim](https://github.com/google/gvisor-containerd-shim), which communicates with the runsc runtime via the [OCI runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/spec.md). Is there something specific you're looking for?

**Comment by younaman** [comment]
@kevinGC Thanks alot! I wonder this because I notice that in a normal container,when you trigger the log system,the container will communicate with containerd and rsyslog,make extra CPU usage.So I wonder know is there simmiliar communication in the gVisor?And I want to know more details.Could you explicate it ?Thank you angain!

**Comment by ianlewis** [comment]
@younaman Not sure if this is what you are asking but, many things such as stdout/stderr log handling will work the same way as normal containers run using runc. Actually retrieving the logs and providing them to a containerd client happens outside of gVisor.

**Comment by younaman** [comment]
@ianlewis Thanks alot! I try to use write to trigger the docker log system successfully!But I have a new question now.If I want to trigger a host syscall(such as write(),not the syscalls of gVisor),how could I write a syscall of gVisor and trigger the host syscall I want?

**Comment by fvoznika** [comment]
It really depends what you're trying to do. If you just want to experiment
with it, you can add a new syscall to the end of the syscall table
<https://github.com/google/gvisor/blob/0dd9ee0d1e08d4207f78ab032a5fde171343c4b4/pkg/sentry/syscalls/linux/linux64_amd64.go#L394>,
let's say syscall(436). In the syscall implementation you can do anything
you want, including making syscalls to the host.


436: syscalls.Supported("mysyscall", MySyscall),
...
func MySyscall(t *kernel.Task, args arch.SyscallArguments) (uintptr,
*kernel.SyscallControl, error) {
  return uintptr(syscall.Getpid()), nil, nil
}

Then, you can run an application inside the sandbox that calls syscall(436)
to invoke your code.

Just be aware that the syscalls issued to the host are tightly controlled.
You may need to add you syscall to this list
<https://github.com/google/gvisor/blob/master/runsc/boot/filter/config.go> to
make it allowed. Otherwise, making the syscall will kill the gVisor
process.

**Comment by younaman** [comment]
@fvoznika Thanks alot! I will try your code at once!If I have some results,I will send you another message!Thank you again!
