### ISSUE TITLE
Implement process_vm_readv and process_vm_writev for the same user only

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#158]
(We can disregard the cases were cap_sys_ptrace is required)

**Comment by alexdesmet** [comment]
Hi,

Just in case you need a real-world example, I have been troubleshooting this for the last couple of days:

I built a Nginx + PHP-FPM container to run Laravel apps on Google Cloud Run. We saw that some requests took very long to complete. Upon inspection, those requests returned a bigger payload then others and were chunked as separate tasks. The first part would complete almost instantly and then wait up until the PHP-FPM slowlog timeout. After that the second part of the response was delivered. If we set the timeout to 10s, it would takes that long for the page to load. 

I ran the container locally and put the code on a cloud VM. Neither one showed the same symptoms.

I then strace'd the syscalls in gvisor and Cloud Run output this message:

> Container Sandbox: Unsupported syscall process_vm_readv(0xf,0x3ede59f9c830,0x1,0x3ede59f9c840,0x1,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/process_vm_readv for more information. 

I believe that the PHP-FPM processes use this syscall to communicate with each other or the PHP-FPM master process. For the time being, we use strace as a MITM for all the syscalls coming from PHP-FPM in order to catch the unsupported one and report it instead of waiting for it to timeout.

**Comment by prattmic** [comment]
> I then strace'd the syscalls in gvisor and Cloud Run output this message:

This message only appeared when running strace, if I understand correctly? strace itself actually uses `process_vm_readv` itself (with a fallback to PTRACE_PEEKDATA when it's not supported in gVisor), so this is expected and unrelated to your application.

**Comment by alexdesmet** [comment]
Yes, that's right. Only when running strace I see the error in the Cloud Run logging. Thanks for clarifying. It's the only syscall I see that is unsupported according to the logs, so I'll look elsewhere. Still odd that putting strace in between resolves the issue.

**Comment by prattmic** [comment]
> Still odd that putting strace in between resolves the issue.

I missed that part, it is odd indeed. To me that seems to suggest some sort of race condition for which strace is slowing things down enough to usually come out on the lucky side of.

**Comment by fvoznika** [comment]
.Net debugger requires `process_vm_readv` to work. @impl, it would be great if you could share a repro case with us to make sure that .Net debugger works correctly once we implement `process_vm_readv`.

**Comment by impl** [comment]
Hi @fvoznika, I actually found that this was an error in their implementation (at least for `createdump` -- I think more substantial debugging with e.g. `lldb` requires a lot more work). I opened a PR at https://github.com/dotnet/runtime/pull/67544 to fix it.

**Comment by zkoopmans** [comment]
This feature has been implemented in [PR7844](https://github.com/google/gvisor/pull/7844). Let me know if there are issues.
