### ISSUE TITLE
Question/issue: Cannot set ApplicationCores with Docker

### ISSUE THREAD

**Issue by ustiugov** [google/gvisor#227]
Dear gVisor team,

Docker's `-cpus` flag is not captured by gVisor as it continues to use all host cores. 

Host: Ubuntu 18.04 kernel 4.15.0-47-generic 
Docker 18.09.6,  build 481bc77
runsc: 
```
runsc version release-20190304.1-185-gff8ed5e6a5a3
spec: 1.0.1-dev
```
Reproduce by: 
docker run --cpus=1 -ti --runtime runsc alpine cat /proc/cpuinfo

Regards,
Dmitrii

**Comment by fvoznika** [comment]
docker's `--cpus` option limits the amount of CPU that can be use, but not which host cores to use. If you need to set `--cpuset-cpus` option to limit which cores are used.

```bash
$ docker run --rm --runtime=runsc --cpuset-cpus=0-1 alpine cat /proc/cpuinfo
processor	: 0
[...]
processor	: 1
[...]
```

**Comment by ustiugov** [comment]
Thank you for the explanation. 
Let's say, I need to launch 100 micro VMs but limit each VM to use just 2 host threads. Would I need to use `--cpuset-cpus=0-1` option of Docker for that?
For the default Docker runtime, this option defines the subset of host cores to be used by their physical ID, AFAIU.

**Comment by fvoznika** [comment]
Let's go over the differences between the options and then see which one works best for your case:
1. `cpus` controls the amount of CPU time your container gets. `--cpus=2` means you get 2 cores worth of CPU time anywhere in the machine. It can be anywhere from 100% of 2 cores, or 50% of 4 cores, or 10% of 20 cores, etc. All cores are available to the container, but they cannot use more time than it's allowed.
1. `cpuset-cpus` limits which cores (or logical processor in case of hyperthread) your container can run on. `--cpuset-cpus=0-1` means that your container can only use logical processor 0 and 1, and no other. When using it, make sure to pair up hyperthreads together.

In general, `cpus` is the better option because it gives flexibility to fill up processors as they become available. Suppose that logical processor 0-3 are at 100%, your container can easily move to a free processor and execute. On the other hand, `cpuset-cpus` can give you better isolation by reducing sharing. If you have a workload that is high priority and you don't want it to be affected by noisy neighbors, then you can use `cpuset-cpus` to dedicate logical processors to it. And of course you can mix them together too.

**Comment by ustiugov** [comment]
Thank you. 
To be more specific, I am studying virtualized processes scheduling efficiency to compare gVisor with QEMU/kvm and Firecracker/kvm alternatives that operate with the concept of vCPU threads. I wonder if there is a way to mimic this scenario with gVisor, I guess we would need to set the maximum host threads count that a gVisor VM (or in fact Go runtime) can use for scheduling guest threads.

**Comment by amscanne** [comment]
A primary intent of gVisor is to provide a virtualized environment while still providing container-like resource semantics: that means a threading model (not vCPU) and memory management model (not a fixed physical address space) that plays nice with the host.

As a result you can't really shoehorn a model with different semantics into a fixed set of X threads. (Just like you can't do that for any other container.) The semantics you have for resources are standard container cgroup semantics as @fvoznika described above.

Can you ask why you want to mimic the VM scenario? Seems like that's contrary to the point of a comparison.

**Comment by ustiugov** [comment]
Hi @amscanne,

Thank you for the prompt response. I am trying to compare gVisor's performance to conventional QEMU/kvm VMs, while running hundreds of toy TCP servers, one per VM. I am trying to decouple virtualization overheads from the overhead of the host scheduler (under load, gVisor ends up spanning more threads than QEMU's vCPUs, for example), that's why I am trying to mimic the vCPU scenario. 

I realize that this scenario may not be a realistic one for production deployment. I assumed this behavior of gVisor because [Kata containers](https://github.com/kata-containers/documentation/blob/master/design/cpu-constraints.md) overload `--cpus` flag of Docker to set up the number of vCPUs, and they also use Docker for deployment. 

Your comment on the [forum](https://groups.google.com/d/msg/gvisor-users/nVQ4_SBxTkc/BBjcg8PpDAAJ) 

> add an appropriate call to runtime.LockOSThread at the top of the mask (*Task).run(...) function in the kernel package. 

is not very clear to me. Could you please elaborate more on how I could do it? I would greatly appreciate it.

**Comment by amscanne** [comment]
I think that isolating scheduling costs alone is a hard problem. (From other kinds of costs.)

The 1:1 mapping described in that forum note will ensure that strictly _more_ host threads are created (as there will be exactly one per application threads, plus some set of Sentry threads not associated with an application thread). It's probably not what you want.

**Comment by ustiugov** [comment]
@amscanne Thank you for the explanation, we would like to try out this configuration among the others. Could you please describe how to configure gVisor for the 1:1 mapping?

**Comment by ianlewis** [comment]
@ustiugov To close the loop, I think @amscanne was saying that it theoretically could be supported but isn't given that it's contrary to gVisor's goals.

I'm going to close this issue since it's old but feel free to reach out on the gitter channel if you have further questions: https://gitter.im/gvisor/community
