### ISSUE TITLE
Add network interface at runtime

### ISSUE THREAD

**Issue by ianlewis** [google/gvisor#2280]
It was noted in [this blog post](https://marcelwiget.blog/2020/03/24/container-isolation-with-kata-and-gvisor-in-docker/) that runsc doesn't allow adding new network interfaces to the sandbox at runtime. runsc should monitor for new network interfaces and make them available to the sandbox.

```
~$ docker run -ti --runtime runsc -d --rm --name r-gvisor --hostname r-gvisor alpine
5d6bbd87aba4f5f2462b0f6273d6db1efe7e988d60be7c569473784920c0da6b

~$ docker network create test-net
be075b84cbb4262f10fbf6bb24e572772847c0ba90e02914ba5e7eb7ab7b085a

~$ docker network connect test-net r-gvisor

~$ docker exec r-gvisor ip addr 
2: eth0: <UP,LOWER_UP> mtu 1500 
    link/generic 02:42:c0:a8:09:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.9.2/32 scope global dynamic 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/32 scope global dynamic
```

**Comment by amscanne** [comment]
We can leave this bug open and document the issue, but I don't think we'll be able to do that easily. I think Docker will just injects a new veth into the namespace, and the sandbox itself will lack the permissions (due to the filters that are installed) to discover and open the veth. Possibly, a gofer could discover the veth and send a bind instance to the sandbox via a connected unix domain socket. (But first we need to build the appropriate framework for network gofers!)
