### ISSUE TITLE
incorrect-looking // +build lines

### ISSUE THREAD

**Issue by rsc** [google/gvisor#2298]
I've been analyzing `// +build` usage in the Go ecosystem and turned up a handful of strange files in the gvisor module zips (not in the repo). Here's one example:

```
$ mkdir /tmp/gvisor
$ cd /tmp/gvisor
$ curl 'https://proxy.golang.org/gvisor.dev/gvisor/@v/v0.0.0-20200328000206-c52860cb85f5.zip' >gv.zip
$ unzip -p gv.zip gvisor.dev/gvisor@v0.0.0-20200328000206-c52860cb85f5/pkg/sleep/sleep_state_autogen.go
// automatically generated by stateify.

// +build amd64 arm64
// +build !race
// +build !amd64,!arm64
// +build go1.11
// +build !go1.15

package sleep
$ 
```

That's the entire file.
By build syntax, those lines mean:

```
(amd64 || arm64) &&
!race &&
(!amd64 && !arm64)&&
go1.11 &&
!go1.15
```

Clearly `(amd64 || arm64) && !amd64 && !arm64` is not satisfiable, so this file will never be built. So it's good that it has no code in it either.

What is going on here? How does this happen?
I'm just curious more than anything. Thanks.

Best,
Russ

**Comment by rsc** [comment]
As I mentioned, there are a whole lot of these kinds of files. `pkg/sentry/arch/arch_state_autogen.go` says:

```
// +build amd64 i386
// +build amd64 i386
// +build i386 amd64 arm64
```

I'm now also curious where `i386` came from.

**Comment by prattmic** [comment]
cc @amscanne 

These are added by tooling added in https://github.com/google/gvisor/commit/95ce8bb4c7ecb23e47e68c60b1de0b99ad8a856d.

Which looking at it now, seems trivially incorrect. It merges the build tags from *all* input files in the package. It's not surprising that those would be incompatible. IIUC, it should be generating unique files for each set of unique build tags.

The `i386` tags come from manually written build tags: https://cs.opensource.google/search?q=%5C%2Bbuild.*i386&ss=gvisor

We never actually build for 386, hence why no one caught these.

**Comment by prattmic** [comment]
Sorry, I was wrong, that does generate different files, but there is definitely some weirdness.

Our `go` branch contains all the generated code. The merge commit there lets us see what Adin's change did: https://github.com/google/gvisor/commit/02dbbe7666661b2d78fd7f13f8131f5fb65c8b8c

**Comment by prattmic** [comment]
Here's a concert example of actual broken generation:

```diff
diff --git a/pkg/sync/norace_unsafe.go b/pkg/sync/norace_unsafe.go
index 006055dd..7cd2fa33 100644
--- a/pkg/sync/norace_unsafe.go
+++ b/pkg/sync/norace_unsafe.go
@@ -11,6 +11,11 @@ import (
        "unsafe"
 )
 
+// +stateify savable
+type fooBar struct {
+       norace int
+}
+
 // RaceEnabled is true if the Go data race detector is enabled.
 const RaceEnabled = false
 
diff --git a/pkg/sync/race_unsafe.go b/pkg/sync/race_unsafe.go
index 31d8fa9a..73d2fb90 100644
--- a/pkg/sync/race_unsafe.go
+++ b/pkg/sync/race_unsafe.go
@@ -12,6 +12,11 @@ import (
        "unsafe"
 )
 
+// +stateify savable
+type fooBar struct {
+       race int
+}
+
 // RaceEnabled is true if the Go data race detector is enabled.
 const RaceEnabled = true
```

```
$ bazel build //pkg/sync
$ cat bazel-bin/pkg/sync/sync_state_autogen_with_imports.go
```

```go
// automatically generated by stateify.

// +build go1.13
// +build !go1.15
// +build go1.12
// +build !go1.15
// +build !race
// +build race
// +build go1.13
// +build !go1.15

package sync

import (
        "gvisor.dev/gvisor/pkg/state"
)

func (x *fooBar) beforeSave() {}
func (x *fooBar) save(m state.Map) {
        x.beforeSave()
        m.Save("norace", &x.norace)
}

func (x *fooBar) afterLoad() {}
func (x *fooBar) load(m state.Map) {
        m.Load("norace", &x.norace)
}

func (x *fooBar) beforeSave() {}
func (x *fooBar) save(m state.Map) {
        x.beforeSave()
        m.Save("race", &x.race)
}

func (x *fooBar) afterLoad() {}
func (x *fooBar) load(m state.Map) {
        m.Load("race", &x.race)
}

func init() {
        state.Register("pkg/sync.fooBar", (*fooBar)(nil), state.Fns{Save: (*fooBar).save, Load: (*fooBar).load})
        state.Register("pkg/sync.fooBar", (*fooBar)(nil), state.Fns{Save: (*fooBar).save, Load: (*fooBar).load})
}
```

**Comment by amscanne** [comment]
The go_stateify tool aggregates files with "special" suffixes (e.g. _amd64.go) and then aggregates the individual AND clauses in those files when producing an output file. So you if you have this:

// foo.go
// +build amd64

// bar.go
// +build amd64

Then you might end up with this:

// autogen.go
// +build amd64
// +build amd64

(The source for the tag bits is [here](https://github.com/google/gvisor/blob/master/tools/tags/tags.go#L24).)

I actually started out parsing all the individual OR clauses in each build line, and then realized that they also could have nested ANDs (e.g. +build foo,bar baz) and got hairy fast.

Instead, I just added all individual AND lines to create a strict intersection. If this causes the file to be excluded from the build (because appropriate definitions are missing), then this should be caught by the build/test. It was the simplest solution.

That said, it looks like there are a few small issues here:

1) We're using i386 somewhere. This is a simple mistake (should be 386?) but we should probably just drop this and merge into amd64. We should just explicitly support only amd64.
2) The !amd64,!aarch case is obviously leading to an bad intersection. The problem here is that these files are not being grouped properly. We just need to decide on an appropriate suffix (_generic?) and add that to the [set of "special" suffixes](https://github.com/google/gvisor/blob/master/tools/bazeldefs/tags.bzl#L3).
3) We need to consistency use the _race and _norace suffixes and add to them to the list as well.

**Comment by rsc** [comment]
There are plenty of fancy conventions or analyses you could use, but why not instead just write out one output file per input file?

**Comment by amscanne** [comment]
> There are plenty of fancy conventions or analyses you could use, but why not instead just write out one output file per input file?

No reason: it seems like a better solution. I just hacked the suffix bits with a few lines of starlark vs. revisiting the guts of the stateify tool. (There was just one ARM-specific struct that broke the build, the dumb version otherwise was working for a long time.)

I think we should fix (1) and (2) anyways, and I'll give this a shot independently to make it more robust.

**Comment by amscanne** [comment]
Okay, it's all coming back to me now. I have to learn about how to declare dynamic lists of outputs for the starlark rules. Ugh. Motivation fading. I'll look into this soon.
