### ISSUE TITLE
checkpoint/restore: not support named unix domain socket 

### ISSUE THREAD

**Issue by yuwang888** [google/gvisor#2300]
i found if used  unix domain socket, restore will failed
# runsc --platform=ptrace run  345332
# ./server &
# runsc --platform=ptrace  restore --image-path=. 345332

running container: starting container: restoring container "345332": restore failed due to external file system state in corruption: gofer device key{device: 0, sdevice: 9pfs-/, inode: 268500} -> 1 conflict in gofer device mappings: cache{key{device: 0, sdevice: 9pfs-/, inode: 1970704} -> 4, key{device: 0, sdevice: 9pfs-/, inode: 268500} -> 61, key{device: 0, sdevice: 9pfs-/, inode: 272429} -> 8, key{device: 0, sdevice: 9pfs-/, inode: 1970815} -> 52, key{device: 0, sdevice: 9pfs-/, inode: 272579} -> 16, key{device: 0, sdevice: 9pfs-/, inode: 272430} -> 9, key{device: 0, sdevice: 9pfs-/, inode: 272428} -> 7, }

here is the server code:
`#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>

#define MAXLINE 80

char *socket_path = "server.socket";

int main(void)
{
    struct sockaddr_un serun, cliun;
    socklen_t cliun_len;
    int listenfd, connfd, size;
    char buf[MAXLINE];
    int i, n;

    if ((listenfd = socket(AF_UNIX, SOCK_STREAM, 0)) < 0) {
        perror("socket error");
        exit(1);
    }

    memset(&serun, 0, sizeof(serun));
    serun.sun_family = AF_UNIX;
    strcpy(serun.sun_path, socket_path);
    size = offsetof(struct sockaddr_un, sun_path) + strlen(serun.sun_path);
    unlink(socket_path);
    if (bind(listenfd, (struct sockaddr *)&serun, size) < 0) {
        perror("bind error");
        exit(1);
    }
    printf("UNIX domain socket bound\n");

    if (listen(listenfd, 20) < 0) {
        perror("listen error");
        exit(1);
    }
    printf("Accepting connections ...\n");
    sleep(1000);
}
`

**Comment by aaronlu** [comment]
Hi, this is what I think is the problem: In overlayBind(), the dirent returned from upper layer(gofer
in this case) isn't returned so wouldn't have its parent set. Instead, a new dirent is created with the overlay inode and gets returned. This caused the problem of childDir's path information being totally wrong and would be regarded as "/" in d.FullName() since it doesn't have parent. Thus, in gofer's SaveInodeMapping(), the socket's path will also be "/" but with a different InodeID compared to the real root and then on restore, gofer's inode afterLoad() will panic with two InodeIDs having the same key.

I have a RFC patch here: https://github.com/aaronlu/gvisor/commit/6975f66e028374a66b8faab99b7ad02e42a68ad1
Please let me know what you think, thanks.

**Comment by ianlewis** [comment]
@aaronlu I don't have the context yet to be able to comment on the patch myself right now but you can submit it as a PR and we can take a look.
