### ISSUE TITLE
runsc exec with detach flag set may cause memory leak

### ISSUE THREAD

**Issue by zhuangel** [google/gvisor#234]
After lots of runsc exec test with detach flag set, we found memory leak in runsc-sandbox process, debug with headprofile, the memory leak mainly found in interface arch.alignBytes, kernel.(*TaskSet).newTask, kernel.(*Kernel).newThreadGroup.

More investigation show the memory leak caused by clearStatus flag in exec command, when detach flag is set, clearStatus will be set as false, then in boot.(*Loader).waitPID, processes will not be freed.

Now we can't free the processes created via runsc exec with detach flag set before we destroy the sandbox container.

**Comment by amscanne** [comment]
This is a leak caused by an external exec with detach correct? Very different from the problem being debugged in #232. This is strange, I don't really understand why we're want clearStatus to be false. It seems to default to true, but this will only happen if the arguments are parsed, which doesn't always happen.

**Comment by prattmic** [comment]
cc @fvoznika @nlacasse 

IIRC, this sounds like it is working as intended. If you runsc exec --detach, then you are expected to eventually runsc wait to wait on the exec'd process.

I could be misremembering though.

**Comment by fvoznika** [comment]
@prattmic  is correct. `runsc exec --detach` requires a call to `runsc wait --pid` to clear the state. Otherwise, there is no way to tell the exit code of the exec'ed process. The `clear-status` flag is internal only, but gives the false impression that it can be set by the caller (I'll rename it).

Does calling `runsc wait --pid` work for your case?

**Comment by zhuangel** [comment]
@fvoznika @prattmic , thanks for your response, I run `runsc wait --rootpid` in my environment, it works, I could see objects freed.

**Comment by zhuangel** [comment]
Hi @fvoznika  @prattmic , one last question, `runsc wait` really free the leaked memory, but my original tests still has memory leak, here are steps to reproduce it.

1. run container with runsc
docker run -it --runtime=runsc centos bash

2. run shell script
#!/bin/bash
for (( i=0; i<1000; i++ ))
do
	docker exec 9ebc904d4a02 ps auxH
done

3. after stop the test, got heap profile of runsc, and found memory leak.
runsc --root=/var/run/docker/runtime-runsc/moby debug -profile-heap=bashtest 9ebc904d4a02

From the `runsc exec` log, I found `docker exec` will invoke `runsc exec` with detach mode, then the clearstatus will be disabled and call-self run `runsc exec` again with clearstatus disabled, this will make the `runsc exec` skip free process resource.

I am not familiar with why docker run `runsc exec` under detach mode, also I didn't find a command from docker to wait a pid in container.

**Comment by fvoznika** [comment]
You're right. `docker exec` doesn't call `runsc wait`, it waits on the child `runsc` process and expects it to be the container init process. So for docker we want to clear the status after exec, while for gvisor-containerd-shim we want the opposite. Let me see how this can be fixed...
