### ISSUE TITLE
bazel-server-start make target fails silently when host uids and gids are unfortunate

### ISSUE THREAD

**Issue by const86** [google/gvisor#2749]
**Description**

Running `make bazel-server-start`, or simply `make runsc`, hangs on me. Internally, it runs detached the bazel docker image, which fails right at the start. That is left undetected, which is a problem on its own.
What fails is the `useradd --uid 1000 --non-unique --no-create-home --gid 1000  --groups 140 -d /home/foo foo` piece of the startup script.. There is no group with GID=140 inside the container. It should be created first and then referenced by name.

**Steps to reproduce**

1. Have /var/run/docker.sock owned by root:docker, where docker has GID=140.
2. Login as a user with UID=1000 and GID=1000 with docker in its supplementary groups list.
3. Run `make runsc`.

**Environment**

Please include the following details of your environment:

*   `runsc -v`
*   `docker version` or `docker info` (if available)
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```
*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)
*   `uname -a`
*   `git describe` (if built from source)
`release-20200511.0-271-g61e687988`
*   `runsc` debug logs (if available)

**Comment by amscanne** [comment]
Well that's a crummy experience. Hopefully #2750 will fix this issue.

**Comment by const86** [comment]
I suspect, the docker group already exists in the image, so you should call the mirroring group something else.

**Comment by amscanne** [comment]
Ah, I actually suspect the issue is that the docker daemon may not be able to honor the --groups 140 request. You're right that  #2750 probably isn't the right solution.

How did you end up running Docker as root:docker? Can you use --groups locally? You should be able to pass any GID there, as it's just assigning it to the init process in the user namespace, I don't believe the contents of /etc/group actually matter here.

**Comment by const86** [comment]
Ubuntu 20.04 runs dockerd as root:docker. I didn't touch its configs.
I tried removing/disabling subject groups tricks, as if my host user's primary group is the same as the group of docker's socket. Even though they are still different. Build goes smoothly. I have no idea why that trick is needed.
Assuming it is needed, I amended your change slightly: create group as `dockerext`, not just `docker`, and it works. The idea is that that group in the container mirrors the external (host's) docker group, hence dockerext.

**Comment by amscanne** [comment]
Wait, so (1) above is not true? Docker is actually running as root:root?

**Comment by ianlewis** [comment]
I'm a bit confused by the adding of a user:group via groupadd and useradd but the container is not actually run as that user id and group id? It seems to be run as root inside the container.
https://github.com/google/gvisor/pull/2750/files#diff-348ea57b6a105f747df20fe317e57674L67

And why do we even care about the docker group inside the container? I assume we're doing all this so that any files created by the bazel server will have an accessible uid:gid owner outside of the container but in that case, shouldn't the user's primary GID be ok? AFAIK adding a docker supplementary group is just so a user has access to the docker socket to create/exec containers but shouldn't have any bearing on the executed container process.

**Comment by amscanne** [comment]
The docker bits are to map the docker socket, and ensure that the user inside the container (which uses the host-native UID, for reasons you mention) is able to talk to that socket from inside the container.

I think this is a repeat of the other problem, and #2771 will fix it.

**Comment by const86** [comment]
> Wait, so (1) above is not true? Docker is actually running as root:root?

Correct. I reworded it appropriately.

**Comment by ayushr2** [comment]
#2771 was merged.
