### ISSUE TITLE
groupadd fails: lock file already used

### ISSUE THREAD

**Issue by kroppt** [google/gvisor#28]
Testing takes like 2 seconds:
- `docker run --runtime=runsc -it ubuntu /bin/bash`
- `root@123456abcdefg:/# test`
- Returns with the following:
```
groupadd: /etc/group.6: lock file already used
groupadd: cannot lock /etc/group; try again later.
```

Nothing seems to show up in the logs when trying with debugging. I confirmed that this is happening both with and without KVM, and only with gVisor.

**Comment by fvoznika** [comment]
Hmm, I can run it just fine. Can you please follow the steps [here](https://github.com/google/gvisor#debugging) and attach the logs to the bug?

**Comment by kroppt** [comment]
I mistyped the testing command; it should be `groupadd test` or whatever other group name.
```
# cat /etc/docker/daemon.json
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": [
		    "--debug-log-dir=/tmp/runsc",
		    "--debug",
		    "--strace"
	    ]
        }
    }
}
$ docker run --runtime=runsc -it ubuntu /bin/bash
root@d11851d18868:/# groupadd test
groupadd: /etc/group.6: lock file already used
groupadd: cannot lock /etc/group; try again later.
root@d11851d18868:/# exit
$
...
# ls /tmp/runsc
ls: cannot access '/tmp/runsc': No such file or directory
```

I had done testing before, such that there existed the log files, but even then I noticed that nothing would show up when testing this issue.

**Comment by fvoznika** [comment]
This is happening because we're not tracking inode link count correctly, so groupadd thinks that it failed to acquire the lock file. If you need a workaround for now, you can enable overlay which will properly account for links. To use it, add `--network=host` to `runtimeArgs` section of your configuration.

This flag will enable an overlay filesystem inside the sandbox. This further isolates the sandbox from the host. All modifications to files are stored in memory inside the sandbox and not committed to the host filesystem.
