### ISSUE TITLE
Expose reference leak checking in runsc API

### ISSUE THREAD

**Issue by iangudger** [google/gvisor#365]
gVisor is getting a new reference leak checker. runsc should allow configuring it.

**Comment by iangudger** [comment]
Leak checking was merged in https://github.com/google/gvisor/commit/45566fa4e4bc55e870ae1d7f80778be8432bdef5.

**Comment by praveensastry** [comment]
Hi, I would like to contribute to this.

**Comment by fvoznika** [comment]
That's great. You could add it as a command-line argument to runsc (code [here](https://github.com/google/gvisor/blob/b6a5b950d28e0b474fdad160b88bc15314cf9259/runsc/main.go#L64)). Possible values are defined [here](https://github.com/google/gvisor/blob/b6a5b950d28e0b474fdad160b88bc15314cf9259/pkg/refs/refcounter.go#L217). The default would be disabled because leak detection has a runtime hit.
