### ISSUE TITLE
`accept` fails on a reset connection

### ISSUE THREAD

**Issue by tamird** [google/gvisor#3780]
- create listener (socket, bind, listen)
- create connector (socket)
- connect connector to listener (connect)
- disable linger on connector (setsockopt(<connector>, SOL_SOCKET, SO_LINGER, {l_onoff=1, l_linger=0}, ...))
- send RST from connector (close)
- accept the connection from listener (accept(<listener>, <non-null addr>, <non-zero len>)

Should succeed, but fails on gVisor with ENOTCONN.

**Comment by hbhasker** [comment]
I am reasonably confident this is a linux upstream bug.

getpeername invokes the getname protoop with peer == 1

https://github.com/torvalds/linux/blob/a1d21081a60dfb7fddf4a38b66d9cef603b317a9/net/socket.c#L1940

But in accept it is called with peer = 2 which means the check in inet_getname that is supposed to return EISNOTCONN will fail because it checks if peer == 1 even though the if clause is guarded by only "if (peer)". 

https://github.com/torvalds/linux/blob/a1d21081a60dfb7fddf4a38b66d9cef603b317a9/net/socket.c#L1759 

In fact calling getpeername on the returned FD from accept fails with ENOTCONN.

**Comment by hbhasker** [comment]
Looking at git history this is how linux has been from at least 2.6.1. So its probably intentional for peer to be tristate and accept calling getname with peer == 2 is intentional so that it doesn't fail. That said it's strange since that means accept will not return ECONNABRT since getname will not fail even if the connection has been aborted.
