### ISSUE TITLE
Internal Unix Domain Sockets are slow

### ISSUE THREAD

**Issue by majek** [google/gvisor#5132]
Here's a chart of throughput of various SOCK_STREAM setups. The idea is to run an echo client who sends bunch of data, and then awaits the response, and measures the latency. Pretty simple stuff.

![numbers-40-4096](https://user-images.githubusercontent.com/63387/102350722-3ebe3400-3f9d-11eb-8241-8478c08f3115.png)

This chart shows ipv4, ipv6, and unix domain sockets performance in two setups:
 - with echo server inside runsc
 - with echo server on the host
Additionally we run it with --network=host or --network=sandbox (Aka netstack)

What stands out is that when both client and server of unix domain sockets are in gvisor the perfomance is 10x worse than any of the other options. 

To reproduce see https://gist.github.com/majek/a2cea2d116fa04aaf167f45f357b4311.

    git clone https://gist.github.com/majek/a2cea2d116fa04aaf167f45f357b4311 echo
    make -C echo
    ./echo/test_perf.sh

**Comment by hbhasker** [comment]
I will try and spend time on this tomorrow but fixes may land only after holidays unless someone else picks it up since I am OOO next couple of weeks.

**Comment by hbhasker** [comment]
Just an update I am able to reproduce your results locally. eg sending 40 blocks of 4MB each over a UDS shows me the following

[+] Wrote 40 bursts of 4.0MiB in 1494.7ms
[-] edge side EOF
[+] Read 160.0MiB in 2495.9ms

vs ipv4 shows the following

[+] Wrote 40 bursts of 4.0MiB in 654.7ms
[-] edge side EOF
[+] Read 160.0MiB in 1656.0ms

**Comment by hbhasker** [comment]
So the issue turns out we never bothered to implement setsockopt SO_RCVBUF/SO_SNDBUF for unix domain sockets. The sockets are defaulting to a 16KB buffer size.

You can see this if you strace the client its doing read/writes of 16KB each in ping pong fashion

See: https://github.com/google/gvisor/blob/1375a87a209ef1a2523ada84254e3a0101afb4f5/pkg/sentry/socket/unix/transport/unix.go#L30

https://github.com/google/gvisor/blob/1375a87a209ef1a2523ada84254e3a0101afb4f5/pkg/sentry/socket/unix/transport/unix.go#L852

Once I changed the initialLimit to 4MB for testing these are the numbers I see
[+] Wrote 40 bursts of 4.0MiB in 332.8ms
[-] edge side EOF
[+] Read 160.0MiB in 1333.1ms

On native (--runtime=runc) here's what I get

[-] edge side EOF
[+] Wrote 40 bursts of 4.0MiB in 107.2ms
[+] Read 160.0MiB in 1107.5ms

Still slower than native but not terrible anymore. 

We will prioritize adding Setsockopt for SO_SND/RCV buf for UDS.

**Comment by hbhasker** [comment]
@nybidari is going to implement these setsockopts.

**Comment by iangudger** [comment]
@nybidari If I recall correctly, the queue size enforcement code may need some work.

**Comment by hbhasker** [comment]
I will pick this up.

**Comment by hbhasker** [comment]
@majek Could you rerun your tests @ HEAD and see if the issue is now resolved?

**Comment by majek** [comment]
Looks good
![image](https://user-images.githubusercontent.com/63387/107956454-194aa800-6f97-11eb-9054-729bb9d3b329.png)

The UDS numbers seem  in the same ballpark as v4/v6 netstack emulation which is what I would have expected. Thanks!

**Comment by hbhasker** [comment]
Marking this closed.
