### ISSUE TITLE
Gvisor CI test on ARM64

### ISSUE THREAD

**Issue by zhlhahaha** [google/gvisor#5248]
Hi @avagin @amscanne I saw there were many ARM64 related patches had merged. And now cross-build for multi-arch binaries and images has enabled. I am wander if there is any plan to expand current CI tests for ARM. We are happy to provide help.

Beside this, I am confused about that gvisor use both buildkite and kokoro for gvisor CI test. Will gvisor CI lane keep using both buildkite and Kokoro, or one of them will be discard?

And the following image is the current gvisor test status summary on ARM64 server.

![image](https://user-images.githubusercontent.com/5655282/104275930-c46eca00-54de-11eb-8000-ed12e9ea44de.png)

Thanks

**Comment by zhlhahaha** [comment]
cc: @lubinszARM

**Comment by amscanne** [comment]
Hey @zhlhahaha, yes, we have been working to get the ARM pieces up to par with the x86_64 infrastructure. @avagin has already added a virtualized ARM smoke test ([example](https://buildkite.com/gvisor/pipeline/builds/1307#42d6c558-9b13-45f3-b29b-4d7fba8f2338)).

To provide some context on the Kokoro/buildkite question: Kokoro is a Google-internal tool for test orchestration. I've been migrating all the tests to BuildKite in order to improve:
- Openness of the infrastructure (less internally tooling)
- Flexibility of the workflows (you can just edit .buildkite/pipeline.yaml)
- Some scalability for presubmits (we now have full runtime tests for each commit)

This migration is nearly complete, and the Kokoro tests should no longer be running as part of presubmits.

There is one more reason to use BuildKite -- it *does* enable proper, physical ARM servers! We definitely want to do this and add it to the pipeline. However, it is critical that the pipeline is *reliable*, which typically means that the server deployments should be automated in some way (e.g. "auto-healing").

If you have a good way to get a good number of ARM instances, then we'd love to add them to pool and add ARM-based tests to the pipeline. (We did already have the ARM instance registered with the pipeline, but are just thinking about how to make this more reliable and scalable.) Let me know your thoughts!

**Comment by zhlhahaha** [comment]
> Hey @zhlhahaha, yes, we have been working to get the ARM pieces up to par with the x86_64 infrastructure. @avagin has already added a virtualized ARM smoke test ([example](https://buildkite.com/gvisor/pipeline/builds/1307#42d6c558-9b13-45f3-b29b-4d7fba8f2338)).
> 
> To provide some context on the Kokoro/buildkite question: Kokoro is a Google-internal tool for test orchestration. I've been migrating all the tests to BuildKite in order to improve:
> 
> * Openness of the infrastructure (less internally tooling)
> * Flexibility of the workflows (you can just edit .buildkite/pipeline.yaml)
> * Some scalability for presubmits (we now have full runtime tests for each commit)
> 
> This migration is nearly complete, and the Kokoro tests should no longer be running as part of presubmits.
> 
> There is one more reason to use BuildKite -- it _does_ enable proper, physical ARM servers! We definitely want to do this and add it to the pipeline. However, it is critical that the pipeline is _reliable_, which typically means that the server deployments should be automated in some way (e.g. "auto-healing").
> 
> If you have a good way to get a good number of ARM instances, then we'd love to add them to pool and add ARM-based tests to the pipeline. (We did already have the ARM instance registered with the pipeline, but are just thinking about how to make this more reliable and scalable.) Let me know your thoughts!

Thank for your quick reply. How many ARM instances are needed?

**Comment by zhlhahaha** [comment]
Since https://github.com/google/gvisor/pull/5275 has merged, most ptrace test failure should be fixed on ARM64

**Comment by zhlhahaha** [comment]
Hi @amscanne @avagin Here is some update for CI test on ARM64
1. ptrace syscall test with error number 524
2. 
2. ptrace syscall test TIMEOUT

**Comment by odidev** [comment]
Please let me know if there is any update on this issue.

**Comment by zkoopmans** [comment]
We have ARM build, smoke, unit and syscall tests running on CI: https://buildkite.com/gvisor/pipeline/builds/18213#_
