### ISSUE TITLE
Use send/receive queues for IP packets

### ISSUE THREAD

**Issue by ghananigans** [google/gvisor#5289]
Currently all packets are received from a link endpoint and handled (sometimes requiring a response to be sent (e.g. pings, link resolution packets)) in the same call stack.

We should look into using receive queues to hold a queue of IP packets to process, and a send queue for a queue of IP packets to send

**Comment by hbhasker** [comment]
IP layer is usually stateless. Why would we want to hold in IP layer. Transport layers have queues but not sure what benefit we gain by having a queue in IP layer.

**Comment by ghanan94** [comment]
The idea is to not synchronously deliver packets that are loopbacked and support receive-side steering

Right now we cannot hold locks when sending packets because loopback may call back into the stack and end up deadlocking if we are sending packet from a socket to itself.

By having an RX queue, we decouple the TX and RX paths for packets through loopback and now locks may be held when sending traffic. This has the benefit of guaranteeing the order of packet sent by a device.

**Comment by ghanan94** [comment]
Note that the RX queue won't be at IP layer. It will be at the device layer similar to TX queues. Just for the opposite direction.

**Comment by kevinGC** [comment]
This sounds like it'll simplify code (don't need to worry as much about deadlocks), but I wonder whether it'll hurt loopback performance. Having loopback traffic be effectively synchronous is probably important to a lot of workloads.

WDYT about enqueueing packets to be sent synchronously _after_ the send finishes? We do something like this in the filesystem: to avoid deadlocks we accumulate a sort of "deferred work" that's run synchronously after the lock is released.
