### ISSUE TITLE
tcpip: type Error does not satisfy the error interface

### ISSUE THREAD

**Issue by josharian** [google/gvisor#5314]
Is this intentional? It seems like it ought to, given its name.

I'm happy to send a PR fixing this.

**Comment by prattmic** [comment]
Yes, this was an intentional decision to prevent accidental use of other error types. This was particularly problematic for system call handling in gVisor, where all errors must ultimately be convertible to an integer errno for return to userspace. Using an arbitrary error could lead to [crash](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/kernel/task_syscall.go;l=402).

That said, I don't know if this thinking has changed for netstack recently (cc @hbhasker). I also thought `tcpip.Error` has a `ToError` method for easy conversion, but it looks like I was misremembering.

**Comment by prattmic** [comment]
Ah, looks like I was thinking of `syserr.Error`. So technically you can do `syserr.TranslateNetstackError(terr).ToError()`, though obviously that's pretty awful.

https://pkg.go.dev/gvisor.dev/gvisor/pkg/syserr#TranslateNetstackError

**Comment by hbhasker** [comment]
Mostly what mpratt@ says: its intentional and we have no plans of changing it due to the possibility of raw errors being propagated to the syscall layer as pointed by Michael.

**Comment by prattmic** [comment]
Thinking a bit out loud here:

gVisor is in the middle of a (very slow) move away from using the `error` type directly, and using these concrete types helps avoid these mistakes (can't find the tracking bug at the moment). When that transition is complete, the syscall implementations should [return](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/kernel/task_syscall.go;l=104;drc=0d54b41e550b452bb990cca55f642169502b82f2) a `syserr.Error` instead of an `error` which we [force back](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/kernel/task_syscall.go;l=402) to a known type.

Right now, having `tcpip.Error` implement `error` would introduce the possibility for someone to accidentally make a function return `error` instead of `tcpip.Error` without noticing and thus potentially accidentally return a different type of error (e.g., from a `strconv` function).

However, once this transition is complete, every function in the system call path will be forced to return a `syserr.Error` (`tcpip.Error` must be explicitly converted). It won't be possible to add an intermediate function that returns `error` without causing obvious compilation errors or adding really ugly/obvious type asserts.

At that point, I think it would be OK to make `tcpip.Error` implement `error`, as we've protected against misuse. gVisor itself would never use it as an `error`, but it would probably be handy to non-gVisor netstack users.
