### ISSUE TITLE
Multi-container doesn't work with cri-o

### ISSUE THREAD

**Issue by jcrowthe** [google/gvisor#626]
The network interface appears to be dropped somewhere during startup. Relevant debug logs:

```
...
I0731 21:55:40.286169    6025 x:0] Enabling loopback interface "lo" with id 1 on addresses [127.0.0.1]
I0731 21:55:40.286229    6025 x:0] Enabling loopback interface "lo" with id 2 on addresses [::1]
I0731 21:55:40.286303    6025 x:0] Enabling interface "eth0" with id 3 on addresses [172.16.6.74] (fe:aa:71:95:6d:40) w/ 1 channels
I0731 21:55:40.286359    6025 x:0] Setting routes [{Destination:127.0.0.0 Mask:255.0.0.0 Gateway: NIC:1} {Destination:::1 Mask:ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff Gateway: NIC:2} {Destination:172.16.6.1 Mask:255.255.255.255 Gateway: NIC:3} {Destination:0.0.0.0 Mask:0.0.0.0 Gateway:172.16.6.1 NIC:3}]
D0731 21:55:40.286796    6025 x:0] urpc: successfully marshalled 37 bytes.
...
```

then ~200ms later

```
...
I0731 21:55:40.577652    6364 x:0] Applying namespace network at path "/proc/6315/ns/net"
W0731 21:55:40.577859    6364 x:0] IPv6 is not supported, skipping: fe80::fcaa:71ff:fe95:6d40/64
W0731 21:55:40.577868    6364 x:0] No IPv4 address found for interface "eth0", skipping
D0731 21:55:40.577870    6364 x:0] Setting up network, config: {FilePayload:{Files:[]} LoopbackLinks:[{Name:lo Addresses:[127.0.0.1] Routes:[{Destination:127.0.0.0 Mask:ff000000 Gateway:<nil>}]} {Name:lo Addresses:[::1] Routes:[{Destination:::1 Mask:ffffffffffffffffffffffffffffffff Gateway:<nil>}]}] FDBasedLinks:[] DefaultGateway:{Route:{Destination:<nil> Mask:<nil> Gateway:<nil>} Name:}}
D0731 21:55:40.577991    6364 x:0] urpc: successfully marshalled 392 bytes.
...
```

As seen in the first snippet, the container IP is known and appears to be set, but then a little later we see that `No IPv4 address found for interface "eth0", skipping`. The results are a container that fully starts up, but has no interfaces outside the loopback interfaces for IPv4/6.

**Other useful information**:

This is a CoreOS box running CRI-o, inside a kubernetes cluster. Runsc is latest nightly as of 7-29. No flags were passed to runsc.

*  Logs: [runsc-logs.tar.gz](https://github.com/google/gvisor/files/3454101/runsc-logs.tar.gz)
*   OS: CoreOS Container Linux. `4.19.43-coreos-r1 #1 SMP Tue Jun 11 07:24:09 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz GenuineIntel GNU/Linux`
*   `CRI-o` version: `v1.13.0`
*   `runsc -v`
```
runsc version release-20190529.1-284-g8da9f8a12c51
spec: 1.0.1-dev
```
*   Reproduction steps: Install CRI-o, download runsc binary from quickstart, configure CRI-o with
```
  [crio.runtime.runtimes.runsc]
  runtime_path = "/usr/local/bin/runsc"
```

**Comment by fvoznika** [comment]
In order to support multi-containers in k8s, `runsc` relies on OCI annotations to determine whether a new pod (aka sandbox process) is being created, and when to create a container inside an existing pod. `cri-o` uses similar, but different annotations than `cri-containerd`. Therefore, `runsc` is unaware that `cri-o` is trying to create a sub-container inside an existing pod. The subcontainer is instead instantiated as a new pod, and attempts to sets up the same network again, causing the error you see above.

[Here is where the supported annotations are defined](https://github.com/google/gvisor/blob/0a246fab80581351309cdfe39ffeeffa00f811b1/runsc/specutils/specutils.go#L331). There is a chance that if you just add `cri-o` annotations to the same checks (e.g. [here](https://github.com/google/gvisor/blob/0a246fab80581351309cdfe39ffeeffa00f811b1/runsc/specutils/specutils.go#L351)) it will work.

The best option however would be to switch to [`cri-containerd`](https://github.com/containerd/cri) and [`gvisor-containerd-shim`](https://github.com/google/gvisor-containerd-shim) which works out of the box.

**Comment by praveensastry** [comment]
@fvoznika Can i give it a go please?

**Comment by fvoznika** [comment]
Sure, please do.
