### ISSUE TITLE
A flag to skip IP deletion

### ISSUE THREAD

**Issue by benbuzbee** [google/gvisor#6549]
### Description

**Problem**
gVisor is unconditionally destructive to the host interface, it deletes IPs there
https://github.com/google/gvisor/blob/7132b9a07b55b1c2944f19bb938878d147785a72/runsc/sandbox/network.go#L246

**Our use case**
 Hashicorp's Nomad supports invoking CNI for an allocation, but it creates a CNI namespace named "<allocation_id>" and if the container crashes, Nomad's default behavior is to restart the container using the same <allocation_id> thus re-using that CNI namespace.

Since gVisor deletes the IPs, this will almost never work. See [my ask from Nomad](https://github.com/hashicorp/nomad/issues/11147).

### Do you have a specific solution in mind?

a --skip-ip-deletion flag that would avoid the linked code. 

Perhaps this has severe security repercussions of which I am unaware, so starting a discussion here

**Comment by benbuzbee** [comment]
I probably don't understand **why** the IPs are deleted in the first place. I naively thought it might just be an extra layer of security - why have the host keep the configuration if it shouldn't use it - but I sense that there is more to it, would you mind elaborating for me why it needs to be deleted? Perhaps that will make an alternative approach make more sense

**Comment by hbhasker** [comment]
GVisor steals the IP from the nic in the namespace and hands it to the user space network stack. The reason we remove the IP from the host nic is because we don't want the host trying to intercept packets. If we leave the IP in place the host will try and respond to incoming packets and in case of TCP it will not have any state and as a result it will send a TCP Reset packet essentially causing abrupt termination of TCP connections.

I would suggest not to reuse these namespaces and instead just create new ones or at least just readd the IP after a container terminates.

**Comment by benbuzbee** [comment]
Ok I understand now, this is integral to gvisor handling the traffic in its sandbox. Unfortunate but makes sense, I dont know enough about the networking stack to suggest any other way of intercepting the traffic before the host kernel; since im guessing this is the best way you found let me learn more heavily in on the Nomad side and use this as an example of why each task needs a unique namespace

**Comment by hbhasker** [comment]
This is probably the easiest way to intercept the traffic. There might be other ways but given the ephemeral nature of these nics and namespaces the effort involved has not been worth it to investigate.

**Comment by hbhasker** [comment]
Closing as this WAI.
