### ISSUE TITLE
Mapping videoloop back using typ=bind .Gofer throws no FD?

### ISSUE THREAD

**Issue by jeyaprabhuj-tts** [google/gvisor#7007]
### Description

    {
      "destination": "/dev/video0",
      "type": "bind",
      "source": "/dev/video0",
      "options": [
        "rbind",
        "rprivate"
      ]
    }

I0105 13:58:33.128341       1 gofer.go:293] Serving "/etc/hostname" mapped on FD 9 (ro: false)
I0105 13:58:33.128348       1 gofer.go:293] Serving "/etc/hosts" mapped on FD 10 (ro: false)
W0105 13:58:33.128355       1 error.go:48] FATAL ERROR: no FD found for mount. Did you forget --io-fd? mount: 4, {/dev/video0 bind /dev/video0 [rbind rprivate]}
no FD found for mount. Did you forget --io-fd? mount: 4, {/dev/video0 bind /dev/video0 [rbind rprivate]}

**Comment by fvoznika** [comment]
`/dev/video0` is a character device and currently cannot be handled by the gofer (file system proxy). File types supported are listed here: [fsgofer.go:checkSupportedFileType()](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/fsgofer/fsgofer.go;l=332;drc=d7dbf65873e2e05723ea23fbfa414742342456e9). Character devices are not supported because they can block indefinitely and the Sentry doesn't expect that.

**Comment by jeyaprabhuj-tts** [comment]
Thanks for your valid input . 

Can you pls let me know if streaming data from outside into sentry sandbox is not recommended?

Our requirement is to use GVisor as sandbox solution in IOT device, where third party customers can deploy their containers.
containers need access to 3 character devices => video,telemetry etc .

Container run ML against video streams .

I defined a new device under sentry\devices\videodev\videodev.go and mapped as character device  inside sentry sandbox .
This has OpenAt,Read,PRead,PRWrite etc. 

Approach 1:
On OpenAt ,Read,PRead start contacting gofer Plan 9 file server and access device file .

Approach 2 :
My plan is to open a connection to streaming server on OpenAt and start receiving streams from server running in host through socket server and return buffer at PRead and Read .

So when we do `cat /dev/video` it is like accessing as usual and people deploying containers can access video streams as usual.


docker run --runtime=runsc --mount type=bind,source=/dev/video0,target=/dev/video0 . Gofer has mounted /device/video0 and I get below traces 

I0111 05:53:53.186432       1 gofer.go:293] Serving "/" mapped to "/root" on FD 7 (ro: false)
**I0111 05:53:53.186442       1 gofer.go:312] Serving "/dev/video0" mapped on FD 8 (ro: false)**
I0111 05:53:53.186451       1 gofer.go:312] Serving "/etc/resolv.conf" mapped on FD 9 (ro: false)
I0111 05:53:53.186458       1 gofer.go:312] Serving "/etc/hostname" mapped on FD 10 (ro: false)
I0111 05:53:53.186464       1 gofer.go:312] Serving "/etc/hosts" mapped on FD 11 (ro: false)

**Comment by fvoznika** [comment]
> Can you pls let me know if streaming data from outside into sentry sandbox is not recommended?

Yes, this seems like a great use case for gVisor!

The give a bit more details, the problem is that if the character device blocks, the Sentry (gVisor's kernel) goroutine will get stuck until the operation completes. If we set the FD as non-blocking, fsgofer lacks the mechanism to notify the Sentry when the operation can be attempted again. One way to workaround it is to make sure an FD is donated to the Sentry, so it can epoll on the FD to know when to attempt the operation again.

Can you please patch #7082, give it try, and let me know if it works for you?

**Comment by jeyaprabhuj-tts** [comment]
Thanks for patch 

Downloaded gvisor - go branch code from repo and patched 

Got below error 

` docker run --runtime=runsc -it --rm --mount type=bind,source=/dev/video0,target=/dev/video1 --privileged  ubuntu bash`

docker: Error response from daemon: OCI runtime start failed: starting container: starting root container: starting sandbox: failed to setupFS: mounting submounts vfs2: mount submount "/dev/video1": failed to mount "/dev/video1" (type: bind): input/output error, opts: &{{false false false false} false {trans=fd,rfdno=10,wfdno=10,cache=remote_revalidating {/dev/video1 false false}} true}: unknown.
ERRO[0000] error waiting for container: context canceled



[patch-error-logs.zip](https://github.com/google/gvisor/files/7922967/patch-error-logs.zip)

**Comment by fvoznika** [comment]
What does `stat /dev/video0` return?

**Comment by jeyaprabhuj-tts** [comment]
ubuntu@ip-172-31-41-104:~/videoforlinux$ stat /dev/video0
  File: /dev/video0
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 5h/5d   Inode: 379         Links: 1     Device type: 51,0
Access: (0660/crw-rw----)  Uid: (    0/    root)   Gid: (   44/   video)
Access: 2022-01-25 04:17:11.388606073 +0000
Modify: 2022-01-25 04:17:11.388606073 +0000
Change: 2022-01-25 04:17:11.388606073 +0000
 Birth: -

**Comment by fvoznika** [comment]
The error indicates that the file type is not being accepted:

```
unknown error: unable to create localFile "/dev/video1": operation not permitted
```

And if the file is indeed `character special file` the fix should have worked. I updated the PR with more logging. Could you please try again? Make sure that a log message like the one below appears in the gofer logs:

```
FOO file type: 16384 (0x4000): supported
```

**Comment by jeyaprabhuj-tts** [comment]
I am not able to build master branch in aarch64 , otherwise could have patched it in master (https://github.com/google/gvisor/issues/7089)
I will patch in current go branch code in aarch64 ubuntu and provide you logs


As an update in amd64 ubuntu it gets mapped but only one stream is received 
Steps 
------------
in host we run 
ffmpeg -re -i sample.mp4 -map 0:v -f v4l2 /dev/video0

and inside sentry or gvisor container do
cat /dev/video0

But we get only one buffer output and not continuous 


Same if we map /dev/random inside container as /dev/video0 , it continuously dumps buffer 
cat /dev/video0

**Comment by fvoznika** [comment]
This is different from the original problem reported. In this case, ffmpeg is creating a regular file and the container is racing with ffmpeg to read the file. `cat` gets to the end of the file before ffmpeg continues to write.

From the strace below, both `fstat(2)` and `read(2)` indicate that the file is 48 bytes in length. The first `read(2)` reads the entire file and the second one returns 0 which indicates `EOF`. If you attempt to read the file again, then it can read the entire content. So it's just racing with ffmpeg and able to read the file faster than it's being written to.

```
I0128 13:17:26.077785  1818623 strace.go:594] [   1:   1] cat E openat(AT_FDCWD /, 0x7f1faf43af71 /dev/video0, O_RDONLY|0x0, 0o0)
I0128 13:17:26.078453  1818623 strace.go:632] [   1:   1] cat X openat(AT_FDCWD /, 0x7f1faf43af71 /dev/video0, O_RDONLY|0x0, 0o0) = 3 (0x3) (644.627µs)
I0128 13:17:26.078501  1818623 strace.go:588] [   1:   1] cat E fstat(0x3 /dev/video0, 0x7f1faf43ac70)
I0128 13:17:26.078701  1818623 strace.go:626] [   1:   1] cat X fstat(0x3 /dev/video0, 0x7f1faf43ac70 {dev=14, ino=1, mode=S_IFREG|0o644, nlink=1, uid=183048, gid=89939, rdev=0, size=48, blksize=4096, blocks=1, atime=2022-01-28 13:17:23.629262564 -0800 PST, mtime=2022-01-28 13:17:23.805261201 -0800 PST, ctime=2022-01-28 13:17:23.805261201 -0800 PST}) = 0 (0x0) (179.184µs)
I0128 13:17:26.078901  1818623 strace.go:591] [   1:   1] cat E read(0x3 /dev/video0, 0x7fb8e0463000, 0x20000)
I0128 13:17:26.078953  1818623 strace.go:629] [   1:   1] cat X read(0x3 /dev/video0, 0x7fb8e0463000 , 0x20000) = 48 (0x30) (37.521µs)
I0128 13:17:26.078985  1818623 strace.go:591] [   1:   1] cat E write(0x1 host:[2], 0x7fb8e0463000 , 0x30)
I0128 13:17:26.079021  1818623 strace.go:629] [   1:   1] cat X write(0x1 host:[2], ..., 0x30) = 48 (0x30) (13.888µs)
I0128 13:17:26.079146  1818623 strace.go:591] [   1:   1] cat E read(0x3 /dev/video0, 0x7fb8e0463000, 0x20000)
I0128 13:17:26.079216  1818623 strace.go:629] [   1:   1] cat X read(0x3 /dev/video0, , 0x20000) = 0 (0x0) (48.63µs)
I0128 13:17:26.079405  1818623 strace.go:585] [   1:   1] cat E close(0x3 /dev/video0)
I0128 13:17:26.079423  1818623 strace.go:623] [   1:   1] cat X close(0x3 /dev/video0) = 0 (0x0) (3.569µs)
```

**Comment by saikiran2021** [comment]
i am able to map the Device but not able get the continuous bytes (input:video running on loop ) only one stream i am receiving. here i am attaching the log file.and external go file.
[videoDevice(logs).zip](https://github.com/google/gvisor/files/7970564/videoDevice.logs.zip)


`package main

import (
	"fmt"
	"syscall"
)

func main() {

	var buffer = make([]byte, 2048)
	fd, err := syscall.Open("/dev/video1", syscall.O_RDONLY, 0777)
	if err != nil {
		fmt.Println("Err:", err)
	}
	for {
		i, _ := syscall.Read(fd, buffer)
		fmt.Print(string(buffer[:i]))
	}
}
`
**docker command:** sudo docker run --runtime=runsc --volume ~/golang/sample01:/sample01 --mount type=bind,source=/dev/video0,target=/dev/video1 -it --rm ubuntu bash

**For your information :**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/79690321/151794164-51a8c38f-1339-416d-a089-261ff3f6f544.png)

**Comment by jeyaprabhuj-tts** [comment]
cat is able to read continuously when used with runsc in docker 

cat /dev/video0 works

**Comment by fvoznika** [comment]
@jeyaprabhuj-tts, the example you gave above `ffmpeg -re -i sample.mp4 -map 0:v -f v4l2 /dev/video0` creates a regular file which is susceptible to the race I described. Both `runsc` and `runc` have the same behavior in my testing. When mapping char devices (like `/dev/random`), runsc can run the stream continuously and can read the entire file depending on timing.

@saikiran2021, thanks for the logs. I can see that `/dev/video1` is indeed a character file in you case:

```
I0131 17:39:10.826619  201680 strace.go:626] [   1:   1] bash X stat(0x557a721e82f0 /dev/video1, 0x7f57c5740900 {dev=15, ino=1, mode=S_IFCHR|0o660, nlink=1, uid=0, gid=44, rdev=0, size=0, blksize=4096, blocks=0, atime=2022-01-31 17:34:31.717050149 +0530 IST, mtime=2022-01-31 17:34:31.717050149 +0530 IST, ctime=2022-01-31 17:34:31.721050193 +0530 IST}) = 0 (0x0) (147.197µs)
```

The caller is able to read several 2048 bytes from the file and then blocks waiting for more data. The last syscall is `read(0x3 /dev/video1, 0xc00008d740, 0x800)` and it never returns. It could be because the character file is not sending more data, or there is a bug somewhere in the code. I would be really helpful if you could provide detailed steps for a repro so I can try it and see why it's blocked (my attempts to read char devices always succeeds). If not possible, I can look into adding a bunch of debug logging to the PR.

```
I0131 17:39:28.405542  201680 strace.go:591] [   6:   6] video E read(0x3 /dev/video1, 0xc000108740, 0x800)
I0131 17:39:28.405593  201680 strace.go:629] [   6:   6] video X read(0x3 /dev/video1, 0xc000108740, 0x800) = 2048 (0x800) (10.589µs)
...
I0131 17:39:28.406829  201680 strace.go:591] [   6:   6] video E read(0x3 /dev/video1, 0xc00008d740, 0x800)
[There is no corresponding 'X read' strace until the sandbox exits] 
```

**Comment by saikiran2021** [comment]
Hi @fvoznika,
  I try master with patch it available on [https://github.com/google/gvisor/pull/7082/files]() 
 with the same example  `ffmpeg -re -i sample.mp4 -map 0:v -f v4l2 /dev/video`

**Comment by fvoznika** [comment]
I think I found the problem. We were not waiting on the host FD for character files. I've updated the PR, please give it another try.

**Comment by saikiran2021** [comment]
@fvoznika  i try with the latest patch. still the same behaviour (only single chunk is  getting )
here i am attaching logs with different approaches .
**Docker-command**
`docker run --runtime=runsc -it --rm --mount type=bind,source=/dev/video0,target=/dev/video1 --privileged ubuntu bash`
[runsc.zip](https://github.com/google/gvisor/files/8012918/runsc.zip)
**Docker-command** here i am trying with go file 
`sudo docker run --runtime=runsc --volume ~/Downloads/video:/sample01 --mount type=bind,source=/dev/video0,target=/dev/video1 -it --rm ubuntu bash`

[runsc-with go file.zip](https://github.com/google/gvisor/files/8012945/runsc-with.go.file.zip)

**Comment by raviprakashg** [comment]
@fvoznika , I tried below caommands to capture the video from laptop inbuilt camera with ffmpeg commands , I am able to capture video inside the container  without runsc.
I am not able to capture the same When i used with runsc mentioned below , I am getting the ** Inappropriate ioctl**  error as shown 

docker run --runtime=runsc --rm -it --mount type=bind,source=/dev/video0,target=/dev/video0  gvisor_ffmpeg_video bash

Command to capture video from /dev/video0
ffmpeg -f v4l2 -video_size 1280x720 -i /dev/video0 -frames 1 out.jpg

Error: 
**[video4linux2,v4l2 @ 0x5597887b6240] ioctl(VIDIOC_QUERYCAP): Inappropriate ioctl for device
/dev/video0: Inappropriate ioctl for device**

**Comment by jeyaprabhuj-tts** [comment]
@fvoznika  
My team execute and got below error.

 I tried below commands to capture the video from laptop inbuilt camera with **ffmpeg** commands , I am able to capture video inside the container without runsc.I am not able to capture the same 

When i used with runsc mentioned below , I am getting the Inappropriate ioctl error as shown

**docker run --runtime=runsc --rm -it --mount type=bind,source=/dev/video0,target=/dev/video0 gvisor_ffmpeg_video bash**
Command to capture video from /dev/video0ffmpeg -f v4l2 -video_size 1280x720 -i /dev/video0 -frames 1 out.jpg
Error:[video4linux2,v4l2 @ 0x5597887b6240] ioctl(VIDIOC_QUERYCAP): Inappropriate ioctl for device/dev/video0: **Inappropriate ioctl for device**

**Comment by fvoznika** [comment]
Sorry for the radio silence here. I updated the PR with more logging so I can try to understand why this is not working. gVisor relies on `epoll(2)` to be notified when data is available. I suspect the problem is related to `epoll(2)` either not being supported or not firing as we expect for the video device. Please patch the updated changes and collect the logs with your repro.

As for the `Inappropriate ioctl for device` error, gVisor doesn't allow `ioctl(2)` to be called on host for security reasons. `ioctl(2)` exposes a large surface from the host that may not be safe or well tested. I'm not familiar with ffmpeg options, but check if there is a way to set it up so if doesn't require `ioctl(2)` calls to the device.

**Comment by prashantmathapati** [comment]
Hello Mr. Voznika, 
Thanks for pointing to this thread. 
I tried building and running opencv Container application with the suggested commit. Below are the observations:
> Docker run Command used: **sudo docker run -it --rm --runtime=runsc -v /dev/video0:/dev/video0 opencv bash** 
> I could see the device mounted as character device (ls /dev shows entry [crw-rw---- 1 root video **0, 0** Jan 10 04:23 video0]). 
> But it is not recognized as video device (major value should be 81 instead of 0). 
> And even Opencv doesnt find any video device inside container. Whereas, with same docker run command with same opencv container image, using runc instead of runsc, video0 device is mapped with correct major & Minor values (ls /dev shows entry [crw-rw----+ 1 root video  **81, 7** Jan 10 04:23 video0]). 
> Please note that Opencv doesnt find any video device inside container, with --mount or -v options even with runc. It works fine only with --device option.

Please find attached two log files for your reference, with Filter applied for "FOO" Keyword. 1st one is with the logs without running OpenCV python script in container. And the second one is with the Python Script running.
Please let me know if any additional Info is required.
[runc_Logs_20Apr_1.txt](https://github.com/google/gvisor/files/8518627/runc_Logs_20Apr_1.txt)
[runc_Logs_20Apr_2.txt](https://github.com/google/gvisor/files/8518629/runc_Logs_20Apr_2.txt)

Best Regards,
Prashant

**Comment by fvoznika** [comment]
Thanks for the quick reply with logs. In your particular case, the main problem is lack of support for the `--device` docker flag (or `Spec.Linux.Devices` from OCI) in gVisor. Without that, volumes that are mounted inside the container do not expose their underlying device number (.e.g opencv is looking for a device with `major number=81 (video4linux)` as you mentioned). If someone is willing to give it a try, we'd be happy to take contributions to add support for it.

**Comment by jeyaprabhuj-tts** [comment]
@fvoznika We have already merged code from runc in gvisor local archive for mounting device in Gofer as device .
Also correct FD is passed to sentry .

Mounted device path is then added to mount file which is read by sentry and shown as charector device .

ls -al /dev
Device is shown as character device but major and minor version is 0 0  and also ioctl ends up in pkg\sentry\vfs\file_description_impl_util.go returning (not a typewriter error)

**Comment by hbhasker** [comment]
@jeyaprabhuj-tts Could you create a PR with your code it will make it easier for us to provide feedback. Reg 2) We would not recommend that as that weakens the sentry security boundary significantly. A compromised sentry will be able to make any syscalls to the host and would expose your host if the sentry for example had a privilege escalation bug that allowed arbitrary code execution in the sentry.

**Comment by prashantmathapati** [comment]
Hello Mr. Voznika (@fvoznika),

Thanks for the reply. I would very much like to contribute for enabling the --device option. If you please point me in right direction, I can try to implement the required changes, do the testing, and submit for your review. 
When I analyzed runc code, specifically for device mapping, I could trace it down to following os level function calls.

dest = rootfs + devicepath
fileMode = -rw-rw----
os.MkdirAll(filepath.Dir(dest), 0o755)
dev = unix.Mkdev(uint32(d.Major), uint32(d.Minor))
unix.Mknod(dest, uint32(fileMode), int(dev))
os.Chown(dest, int(node.Uid), int(node.Gid))
unix.Umask(oldMask)

This is what is enabling video device in runc.
So please guide me on how to enable similar os level function calls in gVisor and also is it the right way to go for it.
Please let me know if any additional things I need to try or any documentation I can refer for this.

Best Regards,
Prashant

**Comment by fvoznika** [comment]
@jeyaprabhuj-tts, @prashantmathapati,

Thanks for looking into this. Since @jeyaprabhuj-tts already has some of the work done to support this, it would be nice to share the code you have so far. In terms of what needs to happen, let me first describe quickly how runsc configures the sandbox/containers. There are 3 different places where configuration happens:

1. **runsc command**: this is done directly in the runsc command that is being executed, e.g. `runsc create`. It runs the context of the caller, which in most case means root with full access to the system. This is where things like cgroups and namespaces are handled. Most of the code is in `container` and `sandbox` packages.
1. **Gofer**: this is a separate process created for each container. It runs in a more restricted environment, but with full access to the filesystem. It handles file system related configuration, e.g. bind mounts. After it's done configuring, it `chroot`s itself into the container's root directory and loses access to anything outside the container. The code is in `runsc/cmd/gofer.go`.
1. **Sandbox**: this code runs inside the sandbox and has very restricted access to the host. It deals with configuring gVisor to make the environment match what the container expects. Examples are creating mount points for the container, setting uid/gid, capabilities, networking, etc. Most of the code is in `runsc/boot` package.

I have to admit that I haven't looked at how `runc` implements `--devices`, but here is my best estimate of what needs to be added:

1. Add code to the Gofer to setup the proper devices inside the container's root. Likely the code that @prashantmathapati posted above. This code here needs to be extremely carefully when handling user-controller paths to ensure it's not giving access to paths outside the container's root. It should also check that the device is `epoll`-able which is required to use within gVisor.
1. Add code in Sandbox to setup gVisor's filesystem to show the device inside the container with the proper configuration, e.g. device numbers. Take a look at `runsc/boot/vfs.go` and `pkg/sentry/fsimpl/gofer`.
1. As you noted, there is no message to query `ioctl(2)` from a gofer file. There needs to be a new message added to the gofer API. Currently, we use 9P to communicate with gofers, but are moving to a different protocol called LISAFS. I recommend focusing on LISAFS only for now given that we're not far from making it the default. `pkg/lisafs` and `runsc/fsgofer/lisafs.go` has many message that you can use as an example to add a new one. The implementation in fsgofer should be as restrictive as possible, using an allow-list of *safe to call* `ioctl`s and restrict it for device files only.

**Comment by jeyaprabhuj-tts** [comment]
@fvoznika @hbhasker 
`_Add code to the Gofer to setup the proper devices inside the container's root. Likely the code that @prashantmathapati posted above. This code here needs to be extremely carefully when handling user-controller paths to ensure it's not giving access to paths outside the container's root. It should also check that the device is epoll-able which is required to use within gVisor._`
### 
**Camera device is mounted as device inside gofer (container namespace) with mknod and not as mount type =bind
Not clear or knowledgable about how to configure as eppollable** 
`
_Add code in Sandbox to setup gVisor's filesystem to show the device inside the container with the proper configuration, e.g. device numbers. Take a look at runsc/boot/vfs.go and pkg/sentry/fsimpl/gofer._`

**VFS has device registry and this entry is based on device implementation inside sentry e.g. ttydevice/tundevice .
Are you suggesting to add a new device implementation like videodev?

On pk/sentry/fsimpl/gofer/special_file.go if we add ioctl api , syscall ioctl from opencv reaches it .
(a dummy implementation which just prints log)
Earlier error "not a typewriter" was not because of missing driver but missing implementation in special_file.go , so code flow reaches to file_description_implt_util.go-> ioctl.
Possible if we add lisafs/gofer client and server implementation this can be forwarded to host device in Gofer .**

`_As you noted, there is no message to query ioctl(2) from a gofer file. There needs to be a new message added to the gofer API. Currently, we use 9P to communicate with gofers, but are moving to a different protocol called LISAFS. I recommend focusing on LISAFS only for now given that we're not far from making it the default. pkg/lisafs and runsc/fsgofer/lisafs.go has many message that you can use as an example to add a new one. The implementation in fsgofer should be as restrictive as possible, using an allow-list of safe to call ioctls and restrict it for device files only._`

_Our analysis
runsc\fsgofer\lisafs.go - implementation of lisafs server
**********Server side Ioctl needs to be added here*************

pkg\lisafs\server.go - lisa server initialization ,start and stop
runsc\cmd\gofer.go - if conf.lisafs is true start lisafs server ,instead of gofer
if conf.Lisafs {
		return g.serveLisafs(spec, conf, root)
	}
pkg\lisafs\handlers.go -  contains list of all handlers exchanged between lisa client(sentry) and server(lisafs server) . E.g. handler OpenAt/Close calls on filedescriptors
**********Client side Ioctl needs to be added here*************
pkg\lisafs\client_file.go -  contains sentry side handlers processing 
**********Client side Ioctl needs to be added here*************_

**Comment by fvoznika** [comment]
> Camera device is mounted as device inside gofer (container namespace) with mknod and not as mount type =bind
Not clear or knowledgable about how to configure as eppollable

`epoll` support is required so that the device works with [`fdnotifier.Notifier`](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/fdnotifier/fdnotifier.go;l=70;drc=16a6afe48fa06a173accc2caac15f3f1a5a3ea3c). [Here](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/syscalls/linux/vfs2/read_write.go;l=106;drc=9768009a797ae71013befe05f8a989d7568eb4a1) for example is where gVisor waits when there is no more data available to read. `gofer.specialFileFD.RegisterEvent()` uses the FD notifier (which uses `epoll`) to detect when data is available to be read again.

Whether or not the device supports `epoll(2)` depends on the underlying driver implementation. To check for it, you can open the device and try to register for `POLLIN | POLLOUT | POLLERR | POLLHUP | POLLRDNORM | POLLWRNORM` events using `epoll_ctl(..., EPOLL_CTL_ADD, ...)`.

> On pk/sentry/fsimpl/gofer/special_file.go if we add ioctl api , syscall ioctl from opencv reaches it .
(a dummy implementation which just prints log)
Earlier error "not a typewriter" was not because of missing driver but missing implementation in special_file.go , so code flow reaches to file_description_implt_util.go-> ioctl.
Possible if we add lisafs/gofer client and server implementation this can be forwarded to host device in Gofer .**

You're in the right place. For testing, you can add `ioct(2)` to the [allowed syscall list](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/boot/filter/config.go;l=27;drc=86ad7d5b5838da1b539e976886d04b93c939ca3d), so that the sentry can issue the syscall directly to the host. Then implement `Ioct` in `specialFileFD` forwarding the call to the host to check if this will work before implementing it all the way to the gofer.

Your LISAFS analysis sounds correct to me.
