### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [google/gvisor#708]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by prattmic** [comment]
Hi Yevgeny!

Fuzzing is great and this is an awesome service you are providing.

We already have continuous fuzzing of the system call interface with syzkaller: https://syzkaller.appspot.com/gvisor

We could also add additional fuzzing of internal Go packages via fuzzit. I think that would be a nice-to-have, but I think we get the most value of syzkaller, since it fuzzes the interface that applications actually use.

**Comment by yevgenypats** [comment]
@prattmic yes, syzkaller is classic for gvisor (but the way syzkaller is fuzzed by go-fuzz which is run by fuzzit, kind of inception:)).

I can try find interesting internal package to fuzz with go-fuzz and post here before implementing.

**Comment by gt6310** [comment]
Go fuzz

**Comment by gt6310** [comment]
Ok

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab
