### ISSUE TITLE
Missing "Origin" field on APT repo

### ISSUE THREAD

**Issue by amarcu5** [google/gvisor#8094]
### Description

The "Origin" field is missing on the APT repo that prevents automated updates using the Debian [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) package.

This should be trivial to add - please see one-line pull request below.

P.S. Apologies if this is seen more as a feature request!

### runsc version

```shell
runsc version release-20221010.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
Docker version 20.10.19, build d85ef84
```

### kubectl (if using Kubernetes)

```shell
Linux ubuntu 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by amscanne** [comment]
Ah, interesting. It can certainly be added. I’m not that familiar with how Origin is commonly used, does it make sense to have it as “gVisor maintainers ($BUILDKIT_BUILD_URL)” for example? Since these packages are all published with an OSS release pipeline, I feel this is more accurate (and this lets us have the specific build as part of the repository metadata).

**Comment by amarcu5** [comment]
I’m unaware of any clear guidance but I’d try and avoid using anything dynamic as changes can cause [issues](https://github.com/nodesource/distributions/issues/755) requiring explicit acceptance. So I’d be fine with e.g. “ gVisor maintainers”. If it helps, here are a few different external repos and their Origins:

Docker: Docker
Elasticsearch: Elastic
Nvidia: NVIDIA
Puppet: Puppetlabs
Ubiquiti: Ubiquiti Networks, Inc.
Valve: Valve Software LLC

**Comment by ayushr2** [comment]
https://github.com/google/gvisor/commit/e3f4ed0bc7abf7b215d322c824fe3929ebedf6c4
