### ISSUE TITLE
Latest release broke unix socket communication

### ISSUE THREAD

**Issue by capnspacehook** [google/gvisor#8126]
### Description

Upgrading to the latest release of gvisor broke Caddy and Tailscale integration. I have a Caddy container that communicates to Tailscale over the unix socket `/var/run/tailscale/tailscaled.sock`. I noticed that the `-fsgofer-host-uds` flag I was passing to `runsc` was deprecated, so I tried using `-host-uds=all` instead but that didn't change anything.

### Steps to reproduce

Install Tailscale. [Enable HTTPS](https://tailscale.com/kb/1153/enabling-https/) and [allow caddy access to the unix socket](https://tailscale.com/kb/1190/caddy-certificates/). Run `caddy:2.6.2-alpine` image and browse to the configured HTTPS domain.

### runsc version

```shell
runsc version release-20221026.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux server 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### runsc debug logs (if available)

[logs.zip](https://github.com/google/gvisor/files/9894382/logs.zip)

**Comment by fvoznika** [comment]
Thanks for attaching logs. Failure setting up the flag would result in `EPERM` errors. You're getting `ENOENT`:

```
I1029 18:36:45.347144   26488 strace.go:600] [   1:   5] caddy E connect(0xf socket:[15], 0xc00016e210 {Family: AF_UNIX, Addr: "/var/run/tailscale/tailscaled.sock"}, 0x25)
D1029 18:36:45.347190   26488 client.go:400] send [channel 0xc000467e60] WalkReq{DirFD: 1, Path: [, ]}
D1029 18:36:45.347313   26488 client.go:400] recv [channel 0xc000467e60] WalkStatResp{Stats: [{Mask:2047 Blksize:4096 Attributes:0 Nlink:1 UID:0 GID:0 Mode:49590 _:0 Ino:1034 Size:0 Blocks:0 AttributesMask:0 Atime:{Sec:1667065949 Nsec:247299805 _:0} Btime:{Sec:0 Nsec:0 _:0} Ctime:{Sec:1667065759 Nsec:5239160 _:0} Mtime:{Sec:1667065759 Nsec:5239160 _:0} RdevMajor:0 RdevMinor:0 DevMajor:0 DevMinor:22}]}
D1029 18:36:45.347332   26488 client.go:400] send [channel 0xc000467e60] ConnectReq{FD: 1, SockType: 1}
D1029 18:36:45.347417   26488 client.go:400] recv [channel 0xc000467e60] ErrorResp{errno: 2}  <== ERROR FROM THE GOFER
I1029 18:36:45.347434   26488 strace.go:638] [   1:   5] caddy X connect(0xf socket:[15], 0xc00016e210 {Family: AF_UNIX, Addr: "/var/run/tailscale/tailscaled.sock"}, 0x25) = 0 (0x0) errno=111 (connection refused) (277.259µs)
```

Has anything else changed in the environment? Can you try running it with the commit prior to the flag change (2ec925ee25c59ffcce138c424bb540b55683486d)?

**Comment by capnspacehook** [comment]
No problem. Nothing changed in my environment prior to upgrading; the container was able to access the Unix socket on the previous version (don't know what that was sorry) and immediately after upgrading gvisor I noticed the error from the Caddy container.

I can try with the commit before, I assume you mean https://github.com/google/gvisor/commit/0eb861df56016eba3758de7afed7181d52e611d0?

Note that I was able to work around the issue by downloading release 20221010.0. I tried downloading 20221017.0, but that 404'd for some reason.

**Comment by fvoznika** [comment]
> I can try with the commit before, I assume you mean https://github.com/google/gvisor/commit/0eb861df56016eba3758de7afed7181d52e611d0?

Yes, https://github.com/google/gvisor/commit/2ec925ee25c59ffcce138c424bb540b55683486d is the change immediately before that :-) You can use this link to download a nightly build before the flag change: https://storage.googleapis.com/gvisor/releases/nightly/2022-10-22/x86_64/runsc

If 2022-10-22 nightly works, then I suspect 226ee9ec81571a90b7e3c3107f947467515f4504 may be the one that broke it.

**Comment by th0m** [comment]
Hi @fvoznika and @capnspacehook, we are also hitting the same issue. We believe it started with release-20221017.0.

**Comment by fvoznika** [comment]
Thanks for the information. I suspect 226ee9ec81571a90b7e3c3107f947467515f4504 is causing the regression. @ayushr2 can you take a look?

**Comment by th0m** [comment]
Indeed @fvoznika I have tested checking out `release-20221017.0` and reverting 226ee9ec81571a90b7e3c3107f947467515f4504 and I can't reproduce the issue anymore.
@ayushr2 feel free to let @capnspacehook or I know if you need anything.

**Comment by ayushr2** [comment]
From logs:
```
    {
      "destination": "/var/run/tailscale/tailscaled.sock",
      "type": "bind",
      "source": "/var/run/tailscale/tailscaled.sock",
      "options": [
        "rbind",
        "rprivate"
      ]
    }
...
D1029 18:36:42.420613   26488 vfs.go:561] Mounting "/var/run/tailscale/tailscaled.sock" to "/run/tailscale/tailscaled.sock", type: bind, options: [rbind rprivate]
W1029 18:36:42.420644   26488 vfs.go:761] ignoring unknown mount option "rprivate"
D1029 18:36:42.420655   26488 client.go:400] send [channel 0xc0004674d0] WalkReq{DirFD: 1, Path: [run, tailscale, tailscaled.sock, ]}
D1029 18:36:42.420931   26488 client.go:400] recv [channel 0xc0004674d0] WalkResp{Status: 0, Inodes: [{ControlFD:12 Stat:{Mask:2047 Blksize:4096 Attributes:0 Nlink:1 UID:0 GID:0 Mode:16877 _:0 Ino:138693 Size:4096 Blocks:8 AttributesMask:0 Atime:{Sec:1663366582 Nsec:113853362 _:0} Btime:{Sec:0 Nsec:0 _:0} Ctime:{Sec:1667068602 Nsec:100034853 _:0} Mtime:{Sec:1667068602 Nsec:100034853 _:0} RdevMajor:0 RdevMinor:0 DevMajor:0 DevMinor:40}}, {ControlFD:13 Stat:{Mask:2047 Blksize:4096 Attributes:0 Nlink:2 UID:0 GID:0 Mode:16877 _:0 Ino:205121 Size:4096 Blocks:8 AttributesMask:0 Atime:{Sec:1667068602 Nsec:100034853 _:0} Btime:{Sec:0 Nsec:0 _:0} Ctime:{Sec:1667068602 Nsec:100034853 _:0} Mtime:{Sec:1667068602 Nsec:100034853 _:0} RdevMajor:0 RdevMinor:0 DevMajor:0 DevMinor:40}}, {ControlFD:14 Stat:{Mask:2047 Blksize:4096 Attributes:0 Nlink:1 UID:0 GID:0 Mode:49590 _:0 Ino:1034 Size:0 Blocks:0 AttributesMask:0 Atime:{Sec:1667065949 Nsec:247299805 _:0} Btime:{Sec:0 Nsec:0 _:0} Ctime:{Sec:1667065759 Nsec:5239160 _:0} Mtime:{Sec:1667065759 Nsec:5239160 _:0} RdevMajor:0 RdevMinor:0 DevMajor:0 DevMinor:22}}, ]}
D1029 18:36:42.421001   26488 client.go:400] send [sockComm 11] MountReq{}
D1029 18:36:42.421133   26488 client.go:400] recv [sockComm 11] MountResp{Root: {ControlFD:1 Stat:{Mask:2047 Blksize:4096 Attributes:0 Nlink:1 UID:0 GID:0 Mode:49590 _:0 Ino:1034 Size:0 Blocks:0 AttributesMask:0 Atime:{Sec:1667065949 Nsec:247299805 _:0} Btime:{Sec:0 Nsec:0 _:0} Ctime:{Sec:1667065759 Nsec:5239160 _:0} Mtime:{Sec:1667065759 Nsec:5239160 _:0} RdevMajor:0 RdevMinor:0 DevMajor:0 DevMinor:22}}, MaxMessageSize: 2093056, SupportedMs: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26 29 30 31]}
D1029 18:36:42.421152   26488 client.go:400] send [sockComm 11] ChannelReq{}
D1029 18:36:42.421280   26488 client.go:400] recv [sockComm 11] ChannelResp{dataOffset: 0, dataLength: 2097152}
D1029 18:36:42.421519   26488 client.go:400] send [channel 0xc000467dd0] ChannelReq{}
D1029 18:36:42.421600   26488 client.go:400] recv [channel 0xc000467dd0] ChannelResp{dataOffset: 2097152, dataLength: 2097152}
I1029 18:36:42.421869   26488 vfs.go:673] Mounted "/var/run/tailscale/tailscaled.sock" to "/run/tailscale/tailscaled.sock" type: bind, internal-options: "trans=fd,rfdno=11,wfdno=11,cache=remote_revalidating,lisafs=true"
```

Why is `/var/run/tailscale/tailscaled.sock` mounted at `/run/tailscale/tailscaled.sock`? Maybe that is why we are getting ENOENT on Connect. I don't understand how 226ee9ec81571a90b7e3c3107f947467515f4504 could be causing this.

**Comment by ayushr2** [comment]
Ah `/var` is a symlink to `/run`. And we correctly resolve the symlink while setting up the mount.

**Comment by ayushr2** [comment]
Investigation notes:

- This use case is well understood and tested. The application is trying to bind mount a socket file from the host and make the container connect to it. We test this in https://cs.opensource.google/gvisor/gvisor/+/master:test/syscalls/linux/connect_external.cc.
- Looking through lisafs connect RPC handler, the only possible way the Connect RPC can return ENOENT is connect(2) syscall failing with that error.
- I suspected it was something to do with the socket being deleted and replaced on the host, in conjunction with the fact that we don't do any revalidation/invalidation for the root dentry of gofer filesystems. Hence the `ENOENT` from connect(2). But that should not be possible. The gofer filesystem has an open FD on the socket file, which will remain valid until the gofer closes that socket FD. I also tried reproducing this but did not reproduce. (Due to certain corp restrictions, we can not install Tailscale and run it. A simpler reproducer would be much appreciated.)
- It is very confusing that connect(2) would return ENOENT for `/proc/self/fd/<socket_fd>`. We know the socket_fd here is valid because logs show that we do a successful `WalkStat` RPC on the socket file, which uses the same socket FD.

**Comment by th0m** [comment]
Thanks for having a look @ayushr2 
I'll get you a minimal reproducer this morning.

**Comment by th0m** [comment]
Ok great, thanks for letting me know @ayushr2

**Comment by ayushr2** [comment]
I think we understand why this is broken. The gofer process does not have a proc filesystem when running. That is why we open an FD to `/proc/self/fd` [here](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/gofer.go;l=216-222;drc=d8aa09e04c4e38155dfcee6ed0495c2b29f604fc) **before** chroot. The chroot causes the /proc filesystem to disappear.

The tests pass because they run with `-TESTONLY-unsafe-nonroot` flag which I think makes the proc filesystem available somehow. This flag makes the above reproducer also pass. That is why this slipped through the cracks.

To fix this, I think we should avoid the chroot. The gofer process is already running in a pivot root with only the container filesystems bind mounted at `/root` and the proc filesystem at `/proc` and `/etc/localtime`. We can instruct the gofers the root filesystem is at `/root`. We should also add a docker test (full end to end test) to ensure this does not happen again. @fvoznika wdyt?

Thanks @avagin for all the help.

**Comment by avagin** [comment]
I think we should not have the entire /proc mount in the gofer mount namespace after initialization stage. We have to bind-mount only parts that we are going to use (e. g. /proc/self/fd).

**Comment by ayushr2** [comment]
This is turning out to be a complicated change. Wonder if it will be easier to just revert 226ee9ec81571a90b7e3c3107f947467515f4504. My intent behind doing that was just keeping fsgofer consistent with directfs. In directfs case, the sandbox has access to the entire procfs: https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/chroot.go;l=106-121;drc=9a96e00f0fb0215d604c72485a85c29f75f48ebc. So directfs can continue to use this `/proc/self/fd/` hack.

No one is really complaining about #1003 so fixing that is not urgent or important. It is unlikely we will even hit that bug in runsc, because the long path would be rejected by the sentry itself. There is no path mappings here.

**Comment by avagin** [comment]
> This is turning out to be a complicated change. 

Could you explain why? If it is about my last comment, it doesn't look something complicated. As for sandbox, it is even more critical to prevent access to random proc files from the context of the sandbox process.

**Comment by ayushr2** [comment]
Yeah it is a bit complicated to set up the bind mounts for parts of procfs. See [this function](https://cs.opensource.google/gvisor/gvisor/+/master:runsc/cmd/gofer.go;l=409;drc=413330510c3308dc8003a633f0fb35b09dbade21). By the time we get to setting up the procfs, there is no procfs, because we have mounted an empty tmpfs mount over the original `/proc`. So we would have to first mount procfs on some temporary location, then bind mount `/proc/self/fd` into the right place and umount it. It is possible, but it will be faster to revert and fix forward when we want.

**Comment by ayushr2** [comment]
@capnspacehook @th0m 226ee9ec81571a90b7e3c3107f947467515f4504 has been reverted in c513ff988e269d3767a6b077a13af46f21e791d4.

**Comment by th0m** [comment]
Great, thanks @ayushr2!

**Comment by ayushr2** [comment]
We did not mark last week's release live due to holidays. Plan on marking it live today.
