### ISSUE TITLE
website: blog RSS feed is misconfigured

### ISSUE THREAD

**Issue by marco-m** [google/gvisor#8223]
Hello,

the blog https://gvisor.dev/blog/ has a feed URL https://gvisor.dev/blog/index.xml.

The "Home Page" in the feed is `http:///`, this has the consequences that all "Article URLs" become invalid, and so from the RSS reader, when reading a given article, one cannot jump to the associated web page.

**Comment by amscanne** [comment]
Hi Marco,

I'm not seeing any instance of "Home Page" or http:/// in the generated xml (which is done completely by jekyll). What I *think* may be happening, is that we are not including some metadata in that XML, and perhaps your reader is constructing a name of the form: "http://<site>/" which ends up rendered as "http:///" (because the refs are relative?). What reader are you using?

**Comment by marco-m** [comment]
Hello Adin,
I am using https://netnewswire.com/ for macOS.
Your question made me try another RSS. I tried https://pypi.org/project/TermFeed/, which is console based.
Invoking `feed https://gvisor.dev/blog/index.xml`, selecting an article in the list and then asking to open the article in the browser, works correctly 🙃.
Looks like a bug in NetNewsWire then. Sorry for the noise, should have tried with another reader before opening the ticket.
