### ISSUE TITLE
checklocks: -test=false does not work

### ISSUE THREAD

**Issue by komuw** [google/gvisor#8596]
### Description

`-test=false` does not ignore test files

### Steps to reproduce

Install the latest checklocks then run it with `-test=false`

go vet -vettool=checklocks -test=false <some-package->

I would expect `checklocks` to ignore test files, but it does note.

**Comment by amscanne** [comment]
I can’t find the documentation for the -test flag, or find how it might be implemented in the vet tool. Is there a good reference for the expected behavior?

**Comment by komuw** [comment]
`checklocks -help`
```sh
checklocks: checks lock preconditions on functions and fields

Usage: checklocks [-flag] [package]

-test
        indicates whether test files should be analyzed, too (default true)
````

**Comment by komuw** [comment]
> Is there a good reference for the expected behavior?

staticcheck[1] also has an option to disable test checking.

1. https://staticcheck.io/docs/running-staticcheck/cli/#tests

**Comment by amscanne** [comment]
This appears to be functionality in singlechecker [1]. If there is a bug in the upstream behavior, it needs to be fixed there. What version are you using? I’m happy to update the dependency if there is a needed fix in the go/x/tools package (but I also just updated).

[1] https://cs.opensource.google/go/x/tools/+/refs/tags/v0.6.0:go/analysis/internal/checker/checker.go;l=82;drc=c1dd25e80b559a5b0e8e2dd7d5bd1e946aa996a0;bpv=0;bpt=1

**Comment by komuw** [comment]
I'm using checklocks version ` v0.0.0-20230224200604-34ff3ebe0556`

**Comment by amscanne** [comment]
This seems to be a bug in the interaction between "go vet" and the "singlechecker" framework, whereby it constructs a unitchecker configuration without consideration of the -test flag, then the singlechecker framework uses the unitchecker configuration as passed [1] (where the package has already been constructed, thus no chance to apply the test flag).

It might be possible to just use the checker inline? E.g. checklocks -test=false ./..., this will respect the test configuration. Otherwise, the solution here is to have a "go vet" that considers the passed -test flag for its -vettool, or a singlechecker configuration that reparses the library config. I'm happy to update to such a fix, but can't really take that on myself.

[1] https://cs.opensource.google/go/x/tools/+/refs/tags/v0.6.0:go/analysis/singlechecker/singlechecker.go;l=70;bpv=1;bpt=0

**Comment by tamird** [comment]
Reproduced this with the current Go development tree and x/tools singlechecker. An upstream cmd/go fix is proposed in https://go-review.googlesource.com/c/go/+/835045, tracked by golang/go#81598.

The change makes go vet apply an advertised boolean -test flag before resolving test-only imports and constructing test packages. The regression fails before the fix and passes after it; the singlechecker reproduction also succeeds with the patched Go command. This is a proposed upstream fix, not a change available in released Go.

Assisted-by: Codex
