### ISSUE TITLE
Is there a way to access host filesystem directly in Sentry

### ISSUE THREAD

**Issue by terenceli** [google/gvisor#8643]
### Description

The performance tax of file access in sentry is quite high(if not very very high), Is there a way to bypass the gofer and access the host file directly?

If not, should we add this as an option? I think  a lot of people will need this.

### Is this feature related to a specific bug?

No

**Comment by EtiennePerot** [comment]
This is not yet ready for production use, but is being worked on by @ayushr2 under the name "directfs": https://github.com/google/gvisor/commit/f9638850c6ac8cb43e0578769f6f6f02097994fe

**Comment by ayushr2** [comment]
We had been working on directfs for a while now. It finally became available in runsc in f9638850c6ac8cb43e0578769f6f6f02097994fe.

If you want to look at the implementation, it was majorly added in b460bf947598c48770b9f83a7618be2dd9e12500. directfs implementation lives along side the gofer client. Instead of making RPCs to the gofer, directfs directly access the filesystem on the host.
