### ISSUE TITLE
Systrap trampoline is too fussy about the `mov eax; syscall` ordering

### ISSUE THREAD

**Issue by jmillikin** [google/gvisor#8894]
### Description

According to the systrap blog post, the trampoline is injected into code matching the `mov sysno, %eax; syscall` pattern. This may work for specific cases (GNU libc?), but in general compilers will write the registers in an unpredictable order.

Would it be possible to have a more flexible trampoline pattern? The first one to come to mind is 5 NOPs followed by`syscall`, which has the same space and could be shimmed into existing wrapper functions at compile time without much trouble.

Attached is a minimal reproduction: a "hello world" binary compiled with Rust v1.64.0. The relevant portion of its `objdump -d` output is:

```
  201260:	49 89 f8             	mov    %rdi,%r8
  201263:	b8 01 00 00 00       	mov    $0x1,%eax
  201268:	89 f7                	mov    %esi,%edi
  20126a:	48 89 d6             	mov    %rdx,%rsi
  20126d:	48 89 ca             	mov    %rcx,%rdx
  201270:	0f 05                	syscall 
```

[hello-amd64.gz](https://github.com/google/gvisor/files/11361581/hello-amd64.gz)

### Steps to reproduce

Compile code that calls `syscall`, and observe that the compiler doesn't always arrange the register writes such that `eax` is the final register to be written.

**Comment by konstantin-s-bogom** [comment]
It's definitely a limitation of this optimization; the Rust example specifically won't be trivial to support because the `mov    $0x1,%eax` is not adjacent to the the `syscall` instruction. These are the intricacies involved with this optimization:
a) The `jmp` needs 7 contiguous bytes.
b) When replacing instructions, we have to keep in mind that multiple threads could be executing them at the same time. In the current implementation we know that a running thread can either be reading the `mov` instruction or the `syscall` instruction. To account for the first case, we replace the first byte with 0x6, which triggers a SIGILL fault that we handle in the installed signal handler; for the second case we make sure the `jmp` trampoline is set past 0x60000, so that the sixth byte of the `jmp` instruction is 0x6. Once we have finished rewriting, we replace the first 0x6 with the necessary byte for `jmp`. 
c) We can't replace instructions atomically because x86 instructions are not guaranteed to be aligned.

About your idea with 5 no-ops preceding syscall: Instead of having 2 possible places to account for, threads can now be hanging on 6 different places. Once we fully replace the instructions with the `jmp`, threads hanging on any of the no-ops (which are not the first no-op) will return to something totally unexpected. 

So I think to support syscall wrapper functions like this, what we'd need is another 5 byte instruction preceding `syscall`, so that the instruction replacement is completed gracefully. The question is, which instruction to use, that would be functionally equivalent to the 5 no-ops...

**Comment by jmillikin** [comment]
Ah, interesting, I hadn't realized the instruction replacement happened as the process was running.

Can I assume that systrap trampoline injection is only enabled for x86-64 binaries? If so, since the `syscall` clobbers r11 and rcx, how about `mov ecx, 0` ? 

```
  201270:	b9 00 00 00 00       	mov    ecx,0x0
  201275:	0f 05                	syscall
```

**Comment by EtiennePerot** [comment]
Correct, this optimization currently only exists for x86-64. IIRC we didn't find an equivalent instruction pattern that had the same properties (popular in compiler outputs && contiguous && large enough to fit the appropriate `jmp` && can be replaced non-atomically during execution) on ARM.

/cc @avagin for the `mov ecx, 0` pattern

**Comment by jmillikin** [comment]
It looks like Rust's inline assembly currently allows control of when the `mov eax` happens, via adjusting the register declaration order. This behavior isn't documented, so I've filed https://github.com/rust-lang/reference/issues/1353 to see if it can be relied on as a guarantee.

No luck so far doing the same with GCC's `__asm__` inline assembly. Here's a quick minimal test case:

```
/* gcc -O2 -c -o hello-c.o hello.c && ld -o hello-c hello-c.o */
static const int STDOUT = 1;
static const int SYSCALL_EXIT = 60;
static const int SYSCALL_WRITE = 1;
static const char message[] = "Hello, world!\n";
static const int message_len = sizeof(message);

void _start() {
	{   /* write(STDOUT, message, message_len) */
		register int         rax __asm__ ("rax") = SYSCALL_WRITE;
		register int         rdi __asm__ ("rdi") = STDOUT;
		register const char *rsi __asm__ ("rsi") = message;
		register int         rdx __asm__ ("rdx") = message_len;
		__asm__ __volatile__ ("syscall"
			: "+r" (rax)
			: "r" (rdi), "r" (rsi), "r" (rdx), "r" (rax)
			: "rcx", "r11");
	}

	{   /* exit(0) */
		register int rax __asm__ ("rax") = SYSCALL_EXIT;
		register int rdi __asm__ ("rdi") = 0;
		__asm__ __volatile__ ("syscall"
			:
			: "r" (rdi), "r" (rax)
			: "rcx", "r11");
	}
}
```

produces this output with GCC v11.3:
```
  401004:	b8 01 00 00 00       	mov    eax,0x1
  401009:	bf 01 00 00 00       	mov    edi,0x1
  40100e:	ba 0f 00 00 00       	mov    edx,0xf
  401013:	48 8d 35 e6 0f 00 00 	lea    rsi,[rip+0xfe6]        # 402000 <message>
  40101a:	0f 05                	syscall 
  40101c:	b8 3c 00 00 00       	mov    eax,0x3c
  401021:	31 ff                	xor    edi,edi
  401023:	0f 05                	syscall 
```

**Comment by bjorn3** [comment]
> The question is, which instruction to use, that would be functionally equivalent to the 5 no-ops...

Nops exists in various sizes. The intel manual lists prefered versions of all sizes up to 15 bytes using for example redundant prefixes.

**Comment by avagin** [comment]
> Correct, this optimization currently only exists for x86-64. IIRC we didn't find an equivalent instruction pattern that had the same properties (popular in compiler outputs && contiguous && large enough to fit the appropriate jmp && can be replaced non-atomically during execution) on ARM.

The good thing about ARM is that all instructions have the same size, so actually we can replace just one instruction there. But another major problem there is that we don't have a way to find a sysmsg structure that is associated with the current thread.
