### ISSUE TITLE
`rm -rf` causes gofer to run very busy

### ISSUE THREAD

**Issue by tanjianfeng** [google/gvisor#898]
The commands to run in container:

$ tar xvf linux-5.3.1.tar.xz > /dev/null
$ rm -rf linux-5.3.1

When the 2nd command runs, gofer process runs very busy with even more than 3000% cpu cycles.

A little bit profiling, we can see that 90%+ cpu cycles are spent on gc.

**Comment by prattmic** [comment]
@nixprime, who has been looking into garbage in the gofer.

I believe this is because getdents + unlink of every file will ultimately cause the gofer to open each.

**Comment by tanjianfeng** [comment]
A little update: we do see similar issue with tree command.
```
$ tar xvf linux-5.3.1.tar.xz > /dev/null
$ tree linux-5.3.1 > /dev/null
```

We did a [heap profile](https://github.com/tanjianfeng/bazel-examples/blob/master/tree_profile002.svg) in the gofer process.
- About 50% of the heap are spent on pathNode in pkg/p9/path_tree.go:newPathNode();
- About 30% of the heap are spent on several structs in pkg/p9/path_tree.go:addChildLocked().

We did a quick hack, SetGCPercent(400) in gofer(500% ~ 600% cpu), it can lower the cpu a lot; and GOGC=off can lower cpu cycles to <100%.

**Comment by nixprime** [comment]
Firstly, here is a sample from stracing `rm -rf linux-5.3.2` showing how `rm` recursively removes a directory that does not in turn contain any subdirectories:

```
newfstatat(5, "xz", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(5, "xz", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
fcntl(3, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
getdents64(3, /* 13 entries */, 32768)  = 432
close(3)                                = 0
openat(5, "xz", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
fcntl(3, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_DUPFD_CLOEXEC, 3)            = 6
getdents64(3, /* 13 entries */, 32768)  = 432
getdents64(3, /* 0 entries */, 32768)   = 0
close(3)                                = 0
unlinkat(6, "xz_dec_bcj.c", 0)          = 0
unlinkat(6, "xz_dec_syms.c", 0)         = 0
unlinkat(6, "xz_dec_test.c", 0)         = 0
unlinkat(6, "xz_private.h", 0)          = 0
unlinkat(6, "xz_dec_stream.c", 0)       = 0
unlinkat(6, "Kconfig", 0)               = 0
unlinkat(6, "xz_dec_lzma2.c", 0)        = 0
unlinkat(6, "xz_stream.h", 0)           = 0
unlinkat(6, "xz_lzma2.h", 0)            = 0
unlinkat(6, "xz_crc32.c", 0)            = 0
unlinkat(6, "Makefile", 0)              = 0
close(6)                                = 0
unlinkat(5, "xz", AT_REMOVEDIR)         = 0
```

Assuming the gofer is not mounted with caching disabled, I believe `gofer.inodeOperations.readdirCache` should at least survive the closing of the directory FD followed by the re-opening of the same FD, so we are concerned only with a single round of Readdir RPCs. (At least two are necessary for every non-empty directory: the first to get entries, the second to get EOF. This is a known 9P defect.)

Each `fsgofer.localFile.Readdir()` heap-allocates a `[]p9.Dirent` (return value); in Go 1.13 the `[]byte` (for `getdents64(2)` output) and `[]string` (for `syscall.ParseDirent()`) appear to be stack-allocated. For each dirent, it also heap-allocates a string (for the dirent's name) and a `[]byte` (for a NUL-terminated copy of the dirent's name, in `statAt() => syscall.BytePtrFromString()`). The invocation of `statat(2)` is necessary because the gofer uses device ID to synthesize a 9P QID (which is in turn used by the sentry to synthesize *another* inode number), but the call to syscall.BytePtrFromString() is technically unnecessary (if we don't care about portability) because struct linux_dirent64::d_name is already NUL-terminated.

Unlink is a little more nuanced. In current VFS, `fs.Dirent.Remove()` forces a completely unnecessary `fs.Dirent` representing the file being removed to be instantiated, which requires a `walkgetattr` RPC and produces a bunch of garbage. VFS2's gofer client will avoid this. The actual `unlinkat` RPC similarly would force an unnecessary `p9.pathNode` to be instantiated, if it wasn't already instantiated by the preceding walk. It also calls `unix.BytePtrFromString()`. In this case we don't already have a NUL-terminated copy of the string handy, but we could use a stack-allocated `[PATH_MAX]byte` instead.

The existence of `p9.pathNode` is a hack to work around rename-synchronization bugs in existing gofers. Ensuring that all existing gofers handle this synchronization correctly remains infeasible, so this probably won't be addressed until we replace p9 for `runsc/fsgofer`.
