### ISSUE TITLE
checklocksignore only seems to work as a postfix field comment

### ISSUE THREAD

**Issue by fasaxc** [google/gvisor#9810]
### Description

I tried using the checklocks vet tool on my own codebase.  I had some fields in a struct that checklocks flagged as "accessed 100% with lock" but the fields were not actually prototected by the lock so I wanted to ignore them.  The `// +checklocksignore` comment seemed to be ignored when I added it like so:
```
type MyStruct {
    lock sync.Mutex
    
    // +checklocksignore
   fieldToIgnore prometheus.Gauge
}
``` 
but, after some experimentation, I found that this did work:
```
type MyStruct {
    lock sync.Mutex
    
   fieldToIgnore prometheus.Gauge // +checklocksignore
}
```

### Steps to reproduce

* Create a struct with a mutex and some fields.
* Access those fields only with the mutex held.
* Run checklocks, it should suggest adding the checklocks pragma.
* Add `// +checklocksignore` above the field instead.
* Rerun checklocks, ti still gives the same output.
* Move comment to end of line containing the field.  Now it works.

**Comment by ayushr2** [comment]
Ack, as per the README for checklocks, your usecase should be working: https://github.com/google/gvisor/blob/07e86e27b07aa0526bf80184b931cb33a7c9bacd/tools/checklocks/README.md?plain=1#L252-L261

I think the issue is that the exeption for `checklocksignore` is saved on the line on which the comment exists: https://github.com/google/gvisor/blob/07e86e27b07aa0526bf80184b931cb33a7c9bacd/tools/checklocks/annotations.go#L75-L78
